### ISSUE TITLE
Communication between modules

### ISSUE THREAD

**Issue by iyilm4z** [ExtCore/ExtCore#102]
Today i gave a try for e-commerce project which uses ExtCore as it’s infrastructure for modularization. Usually i start my projects with some boilerplate functionalities like localization and logging. I created 3 projects which i named as App.Host(webapp), App.Localization(classlib) and App.Logging(classlib). As you may guess Localization and Logging projects were hosted in Host project. Everything was going on well until i realized that i need some clases(entities and services) of Localization project in Logging project and also i need some classes of Logging project in Localization project. Well.. as i know circular dependency is really bad practice and that’s why circular referencing is not allowed in .net. Who has a recommendation to solve this issue?

**Comment by DmitrySikorsky** [comment]
Hi! You can take a look at [Platformus ](https://github.com/Platformus/Platformus)project for the architecture ideas.

In your case, if both A and B projects need some shared classes, you should put them inside the C project.

**Comment by iyilm4z** [comment]
Thanks for replying! I already knew Platfformus but i didn't know it has a solution of solving module communication. When i first check it out it seemed to me a bit complex and it still seems. Dmitry i think that you could provide us a simple example of module communitation(entity, services, composite ui) if it's possible. Thanks in advance.

**Comment by DmitrySikorsky** [comment]
I think this sample might be helpful for you: https://github.com/ExtCore/ExtCore-Sample-Modular-Ui-Adv/tree/master/src

**Comment by iyilm4z** [comment]
Dear Dmitry, i tried to solve my problem on [Modular-Ui-Adv](https://github.com/ExtCore/ExtCore-Sample-Modular-Ui-Adv) project but i got circular dependecy error. Aftern that i did a wide research on the net and i came with terms like Microservices, Event Bus and Composite-UI. There are huge amount of information on these terms but all seem blurring and not clear to me because of my level of understanding. Actually what i want to do is something really simple; to share entities or services or anything which belongs to one module to others. Imagine i put shared classes in Project C which references Project A and B, when Project A needs entities(EF entities) or services(BLL classes) from Project B, which project i will use? I can't use Project C because it references Project A, I can use Project B but why i put shared classes in Project C then? Well i think i'm on wrong way or i'm trying to do something not possible. All i want to do is to have ExtCore Modules which have their own Controllers, Views, Services, Entities, View Models to manage my application parts which are like Localization, Catalog, Customers, Orders so on and so forth. But these modules cant work without sharing some classes. For example Every module needs Localization module and Logging. It may be called microservices but i'm not sure. Well.. maybe i should make a demo and show you what i wanna try to do with ExtCore.

**Comment by cybernexus** [comment]
@iyilm4z try this.... http://docs.extcore.net/en/latest/fundamentals/unified_extension_structure.html

Basically, each module can have multiple projects where you can put the shared bits and then reference those lighter weight projects in other modules.

You mentioned localization, here is a very simple overview example:

YourProject.Localization // primary module project
YourProject.Localization.Data.Abstractions // project that holds service and repository interfaces (typically might be referenced in other projects)
YourProject.Localization.Data.Entities // project that holds pocos (typically might be referenced in other projects)
YourProject.Localization.Data.Implementation // project that holds the abstraction projects  implementation classes
YourProject.Localization.SomeOtherClass // any other class you may want to share with other projects

**Comment by iyilm4z** [comment]
@cybernexus i appreciated your concern! I know this is how [Platformus](https://github.com/Platformus/Platformus) structured. However dear friend maybe i'm someone who understand things hard. If you can please provide us very simple example like you mentioned. Just 3 modules and one host, that's all! I will be really pleased bro!

**Comment by DmitrySikorsky** [comment]
@iyilm4z, if you want to have 2 extensions (A and B), and each of them needs to have entities, put them inside the A.Data.Entities and B.Data.Entities. If entities of the B extension need to know about entities from the A extension, add dependency on A.Data.Entities inside the B.Data.Entities projct. That's all. If at the same time your A extension needs to know about entities from the B extension, you have wrong application architecture and have to fix it first.

So I would suggest you to start thinking from the most shared extensions. Like create some basic extension. It is Barebone in the Platformus. It contains things and classes all other extensions need.

Then, for example, create Globalization extension. All the localized extensions will need it. Etc.

**Comment by iyilm4z** [comment]
@DmitrySikorsky @cybernexus Thanks for all of your concerns! Sure i'm doing somethings wrong. I will take your advices.

**Comment by Mardoxx** [comment]
@DmitrySikorsky 
>If at the same time your A extension needs to know about entities from the B extension, you have wrong application architecture and have to fix it first.

What would you suggest for, say, a reporting extension where it would require joins between data from different extensions.

**Comment by DmitrySikorsky** [comment]
@Mardoxx this is normal situation. Just add dependencies on extension A and on extension B to your reporting extension. (It would be wrong to have need to add dependency on reporting extension to extension A or B at the same time.)

**Comment by Mardoxx** [comment]
@DmitrySikorsky Hmm... In the context of using extensions to allow neat separation of data models (i.e. you are using the same database to for all your data) it's not an ideal solution is it? 

Doing this orchestration on the consumer (i.e. not directly on the db and instead collating records from each service and joining them in memory) seems .. almost wrong?

l suppose in this instance it would be a trade-off  between plug-ability & separation and letting a DB do its job.

Feels like I'm missing some intuition here.

**Comment by DmitrySikorsky** [comment]
@iyilm4z Please take a look at https://github.com/ExtCore/ExtCore-Sample-Accounting/blob/master/src/Balance/Balance.csproj

This extension shows balance (income minues expenses). It has to "know" about other 2 extensions with incomes and expenses.

**Comment by DmitrySikorsky** [comment]
@Mardoxx could you describe your task? Because there might be many different solutions, but it is difficult to choose the best one without understanding the task.

But still.

You can have extensions. Sometimes they can be fully independent, sometimes they can not. Example. My Platformus project has image processing services (it is /img route which receives the image URL, downloads it, resizes and writes result into response). You call it like /img?url=some url&w=100&h=100.


Of course, you can remove this extension and replace it with your one. While it has the same parameters list, you won't  have any problems.

This extension is not related to anything.

But also Platformus has Globalization extension, which describes everything you need to build localized entities. All the extension that need content localization have to have dependency on that extension.

So if your extension normally should "know" about entities from another extension (to build reports, for example), it is normal to add dependency.

**Comment by iyilm4z** [comment]
@DmitrySikorsky Thanks for information about already existing sample. Now it's all clear. Actually what i want was something different(maybe microservices) but i realized that i made a mistake. Anyway  soon i will share a repo by using ExtCore which shows "communication between modules" in a detailed way.

**Comment by DmitrySikorsky** [comment]
@iyilm4z Good! Then I will close this  issue for now. Feel free to reopen it any moment if you have any additional questions.
