### ISSUE TITLE
Add support for full .NET framework

### ISSUE THREAD

**Issue by mariuszjamro** [ExtCore/ExtCore#103]
Currently you cannot install the ExtCore nuget packages in a ASP.NET Core project targeting full .NET framework (not the .NET Core). The error is:

     Package ExtCore.WebApplication 3.1.0 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package ExtCore.WebApplication 3.1.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)

Will it be possible to add entry for the full .NET to the published nuget packages?

**Comment by DmitrySikorsky** [comment]
I think to fix that we need to change

<TargetFramework>netcoreapp2.0</TargetFramework>

to be

<TargetFramework>netcoreapp2.0;net471</TargetFramework>

right?

I need to test that.

**Comment by DmitrySikorsky** [comment]
Hm, but I'm not sure that it is possible: https://stackoverflow.com/questions/46531784/how-to-target-netcoreapp2-0-and-net461-in-the-same-project

**Comment by mariuszjamro** [comment]
The problem is caused by using Microsoft.AspNetCore.All metapackage as a dependancy on ExtCore. It is compatible only with `netcoreapp2.0` (that's [by design](https://github.com/aspnet/Announcements/issues/243)). So ExtCore cannot be used in projects targetting anything else. 

A side-problem is that `Microsoft.AspNetCore.All` contains EntityFramework Core, so even if you're using ASP.NET Core without EF Core (for example with EF6), ExtCore will still bring a depandancy of EF Core in project using it.

I think libraries should target `netstandard2.0` instead of `netcoreapp2.0` and consume individual AspNetCore nuget packages instead of the giant metapackage. This way it will run on any platform supporting [.NET Standard 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) (which includes .NET Core 2.0+ and .NET Framework 4.6.1+) and won't contain unnecessary dependancies ([see this](https://stackoverflow.com/a/46165337/342473))

I made the necessary changes on my branch mariuszjamro/ExtCore@ce86efd767e2f6cc2a7a22afabe4dea047dab79b. I'll test it in my project and let you know if you're open for a PR.

**Comment by jinhong-** [comment]
@mariuszjamro How did your testing go with .NET Standard 2.0?
