### ISSUE TITLE
Extcore module in nuget packages?

### ISSUE THREAD

**Issue by murbanowicz** [ExtCore/ExtCore#106]
Hi,

I just found this project and looks quite promising but I am not sure if I  use it the way which I want to use.

I would like to be able to have my extensions as nuget packages so it would be easier to manage them across different projects containing some of them.

Is it possible? If so, any examples? 
I went through some of your examples and also looked at your Platformus but it all has code in one repo.

I will appreciate any answers.

Maybe would be worth to create gitter channel to avoid asking questions as issues?

**Comment by DmitrySikorsky** [comment]
Hi! We have a Gitter channel: https://gitter.im/ExtCore/ExtCore

And yes, it is possible to put ExtCore extensions to NuGet with no problems. Platformus might be a good example. I can tell you more if you have any questions.

**Comment by murbanowicz** [comment]
I have asked the questions there but it's quiet... 
I cannot figure it out at all to be honest. 

This library looks great, but if you could improve docs to make it easier to dive in - you would gain much more users!

**Comment by postb99** [comment]
Hi Marek, I'm another extcore user, I admit I rely often more on samples than docs. What points would you improve ? Dmitry needs help and you're welcome. Please contact him.

**Comment by murbanowicz** [comment]
@postb99 - There should be definitely better Getting Started section with complete explanation together with code. 
Some day when I will feel comfortable enough with ExtCore I may participate in docs and maybe code too as I am looking for some .NET Core project to participate in, but I am not there yet.

**Comment by DmitrySikorsky** [comment]
@murbanowicz Hi Marek! I agree with you that we need a better docs. From your point of view, what articles are missed there to have better understanding of the project? You will help me if you write topics.

As @postb99 said, I had time problems. I also have another (much bigger) open source project - Platformus, and I have to write docs there too. So, I  really need any help. Even just with ideas.

**Comment by murbanowicz** [comment]
@DmitrySikorsky Hi,

I will then try to help with topics and at some point I will try to help with some docs/features when I'll be ready.

Getting started - example of code of the main app and extension (I know we have examples but...) with explanation of the setup of both - what is required in extension to make it discovarable & working and what is optional. 

I think some explanation how it has to be referenced when using extension from Nuget package as I think the whole great idea of extensions (I prefer to call them modules) is making most profit when each extension can be in the Nuget package so the code can be easiermaintainable.
Maybe x.1 - using extension from the solution x.2 - using extension from the Nuget package ?

I will be going through the process of building the complete 'platform' as I am now starting large project which will consist few modules (each quite large) so I should be able to point out what is missing in docs and help with topics and maybe even writing something which you can use as a base and tweak instead of writing it from scratch?

Other thing which I am not sure if it is related but maybe worth asking - do you have any good idea, maybe coming from platformus, about theming/styling the app? What if the extension/module would consist the partial views, which then can be used in the main app? Is that good/best way? If so, how can I use partials from extension in the main app?

**Comment by DmitrySikorsky** [comment]
@murbanowicz Thank you!

Have you seen this: http://docs.extcore.net/en/latest/getting_started/index.html ?

Maybe it should be improved, I agree.

What about theming. This task can be fixed using different approaches. One of them. You create ITheme interface, which provides properties (collections of the styles that must be rendered on the page).

Then, in different 2 projects you implement this interface and return different style files. In this case you will be able to make your modules possible to add additional styles, scripts etc.

You can also use partials to fix that. You can render some partial with styles in the main web app, but put that partial in the extension package. Having different packages with the same partial (but different styles) you will be able to  change the current theme.

**Comment by murbanowicz** [comment]
I think I missed the point 3.. So if my extension is nuget package and it is referenced in csproj it's enough to get it discovered?

About the theming - the thing is that I do not want to change css only. I want to be able to create completely new layouts etc but using prepared partials from my module. 
1. I do not get how can I pass the

**Comment by Xarkam** [comment]
A bit off topic but I thought the doc was generated with docfx.

I should maybe do a doc if we use Visual Studio Code for build app with extcore ect ...

**Comment by DmitrySikorsky** [comment]
@murbanowicz The menu items feature is not something special in ExtCore. You just should 'start thinking' in modular way, if I can say this way :) Look. Define your interface. Put it in the shared project. That interface should define some property that returns something. For example, menu items.

Then you just get ALL the implementations of that interface from ALL the modules. It is done using the ExtCore with 1 line of code. And using method defined in the interface you easily get all the menu items from all the modules. It works not only for the menu items, you can use it for everything. You can define service interface in one package and have different implementations in different packages. And then you put  specific dll or reference some NuGet package with specific implementation. And when you find all the implementations of the interface you will get them from the available modules.

You can use that approach for the views too. Just get the available implementation, it can return array of the view names.

Partial views (and regular ones) work the same way as they are in the main web app. The only point is that you must make them resources in the extension to be embedded into the module while build.

**Comment by Xarkam** [comment]
@DmitrySikorsky preceded me: D

Yes partial views are there to make page parts consistent.

You can always look at my Softinux Base project (which is not yet as big as Platformus) to see how to embed resources and use partial and non-partial pages run.

In Softinux Base, Barebone is the entry point for the application. This is certainly the good start point for look the code logic

About the menus, my wife added the possibility to add an icon in the menu items.
It's not over yet, we have not proposed it as a new feature of ExtCore

**Comment by postb99** [comment]
I wonder whether the barebone should be in extcore rather than in Base or Platformus project... Maybe some common code should go to extcore, extcore.barebone :-)

**Comment by DmitrySikorsky** [comment]
@postb99 you know, I think ExtCore should remain as simple as possible, but maybe we could have another project on top of the ExtCore, like barebone modular application. I was thinking even about having VS template or something. To make it very easy to create ExtCore-based modular application.

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please, feel free to reopen it if you have any additional questions or information.
