### ISSUE TITLE
How to configure e.g. mounting point of the extension? 

### ISSUE THREAD

**Issue by murbanowicz** [ExtCore/ExtCore#107]
Hi,

I am getting to the point where I think I am getting your concepts and it looks like something which I could use to build my platform more efficiently. 
 
I am wondering about the configuration of the extension from the level of main app?
Lets say I have a module which expose many api endpoints and sometimes I will want all of them to be directly under / path but sometimes I may want them to be under /api/mymodule  . 
How can I achieve that?

I have some other questions which are worth asking I think but would be much better to just chat on gitter if you're available any time soon

**Comment by DmitrySikorsky** [comment]
To configure your extension the best way is to use IOption feature. For example, that is how it is used by the ExtCore.Data extension:

https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.Data.EntityFramework/StorageContextBase.cs#L30

And this is how it is configured:

https://github.com/ExtCore/ExtCore-Sample-Data/blob/master/src/WebApplication/Startup.cs#L31

**Comment by murbanowicz** [comment]
Thats right. 
So as I understand extcore does not configure the path of extensions etc under the special path, so eg TestController from my module with mount under the /test/ of the main app?

**Comment by DmitrySikorsky** [comment]
Yes. You can use areas to add some extra path part. Or you can use special routes for that. Each extension can define routes.

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please, feel free to reopen it if you have any additional questions or information.
