### ISSUE TITLE
DLL not resolved by the Razor View

### ISSUE THREAD

**Issue by Hypenate** [ExtCore/ExtCore#108]
**Output**

- All DLL's are found (Output of ExtCore.WebApplication:Information)
_Loaded 'D:\DLLCore\netcoreapp2.0\Extension.Data.Abstractions.dll'.
Loaded 'D:\DLLCore\netcoreapp2.0\Extension.Data.Entities.dll'. 
Loaded 'D:\DLLCore\netcoreapp2.0\Extension.Data.EntityFramework.Sql.dll'. 
Loaded 'D:\DLLCore\netcoreapp2.0\Extension.dll'. Symbols loaded._

- The Razor View doesn't find the reference
_Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred: The type or namespace name 'Extension' could not be found_

**Result**
- A blank page

**Steps to reproduce**

- Failing Index.cshtml
```
@model List<Extension.Data.Entities.Person>

@foreach (var item in Model)
{
  <p>@item.Id @item.Name</p>
}
```

- Working Index.cshtml (without the model, and losing intellisense in the view)
```
@foreach (var item in Model)
{
  <p>@item.Id @item.Name</p>
}
```

**VS Solution**
[WebAreasCore.zip](https://github.com/ExtCore/ExtCore/files/1727283/WebAreasCore.zip)

**Comment by Xarkam** [comment]
Hello, 

I don't have error
![image](https://user-images.githubusercontent.com/331816/36263829-63181bac-126b-11e8-838d-344da2954cd6.png)

But, I have a 404 on run the project. The code does not go into the controller

[WebAreasCore.zip](https://github.com/ExtCore/ExtCore/files/1728200/WebAreasCore.zip)

**Comment by Hypenate** [comment]
@Xarkam It's when you run the project with "@model List<Extension.Data.Entities.Person>" that the page is blank/empty.

**Comment by DmitrySikorsky** [comment]
So, I have tested your code and it works with no problems. If I just build and rut it, I have 404 error. That's because extension is not added to the application. If I add dependencies to the Extension and Extension.Data.EntityFramework.Sql, it just works with no problems.

**Comment by Xarkam** [comment]
@DmitrySikorsky yes. That's what I answered but he seems not to have read all my answer.
I do not waste my time if my answers are not read

**Comment by DmitrySikorsky** [comment]
![2018-02-16](https://user-images.githubusercontent.com/6570196/36300294-67f26f94-1309-11e8-85da-c3ca0dcd85c3.png)

**Comment by DmitrySikorsky** [comment]
@Xarkam I think I'm closing this for now, because I can't find any problem here. @Hypenate feel free to reopen if you still have questions.

**Comment by Hypenate** [comment]
@DmitrySikorsky "That's because extension is not added to the application"
I tought the whole concept of extCore is that it would add the DLL on runtime?

**Comment by Hypenate** [comment]
The problem relates to this [issue](https://github.com/dotnet/core-setup/issues/2981#issuecomment-322572374).

Because I placed my DLL's on another drive, the .NET core framework was unable to find it.
So I placed the DLL's in my application root and now everything works!

**Comment by DmitrySikorsky** [comment]
Thank you for this info!

BTW. You CAN put dlls into the subfolders, but you have to set IncludingSubpaths parameter to true in order to make it work: https://github.com/ExtCore/ExtCore-Sample/blob/master/src/WebApplication/appsettings.json#L7
