### ISSUE TITLE
How to config StorageContext for paging Sql Server 2008 R2 ?

### ISSUE THREAD

**Issue by AppCj** [ExtCore/ExtCore#109]
Hi, 

I Need to configure UseRowNumberForPaging() for paging on sql2008r2.

For that I need to configure StorageContext on ExtCore.Data.EntityFramework.SqlServer

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    base.OnConfiguring(optionsBuilder);
    if (string.IsNullOrEmpty(this.MigrationsAssembly))
        optionsBuilder.UseSqlServer(this.ConnectionString, options =>{
            // CONFIGURE HERE
            **options.UseRowNumberForPaging();**
        });
    else
    {
        optionsBuilder.UseSqlServer(
            this.ConnectionString,
            options =>
            {
                options.MigrationsAssembly(this.MigrationsAssembly);
                // CONFIGURE HERE
                **options.UseRowNumberForPaging();**
            }
        );
    }
}

What can I do to pass this configuration to the ExtCore, or to achieve this goal?

**Comment by DmitrySikorsky** [comment]
Hi! This is good question. For now you can just copy this class (https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.Data.EntityFramework.SqlServer/StorageContext.cs#L13), add that line of code manually, and then register it inside the DI after ExtCore.Data registers its own one.


This action runs with priority = 1000 and registers found IStorageContext. So you can run your action with priority = 1010 and register new one. It will work. But I have to think about how to make configuration process easier.

PS: Sorry that I answer this issue with so big delay, I just missed the notification and didn't see it.

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please, feel free to reopen it if you have any additional questions or information.
