### ISSUE TITLE
Asp.net core WebApi and Angular 5 sample

### ISSUE THREAD

**Issue by Hamix** [ExtCore/ExtCore#111]
Hey
Can you provide a sample using web api and angular 5?
how can i modularize the ClientApp folder?

**Comment by Hamix** [comment]
@Xarkam  Thanks it's great template but i need it modular. 
for instance The Customers part have separated views, db modals, controllers and etc in a dll that I'm able to update or remove it from my application without any errors. Still  great template I'll use it for quick projects.

**Comment by Xarkam** [comment]
There is also this: https://docs.microsoft.com/en-us/aspnet/core/spa/angular?view=aspnetcore-2.1&tabs=netcore-cli
Since each extension can be an asp.net application, it would be possible to go through this template.

**Comment by DmitrySikorsky** [comment]
Hi! I really think I should have such sample. And this task is already in my TODO list.

**Comment by Hamix** [comment]
@DmitrySikorsky  I'm looking forward to that. Thank you.

**Comment by DmitrySikorsky** [comment]
Currently have no time to implement a demo, I will spend available time to implement features from the milestones. I would appreciate if you find some time to provide an example for others if you have already deal with that. Thanks.
