### ISSUE TITLE
ExtExtensionManager.GetInstance give null with singleton class

### ISSUE THREAD

**Issue by niconico49** [ExtCore/ExtCore#112]
from yours sample project about Services "ExtCore framework 3.2.0 sample web application that registers a service inside the extension;" if, inside the method:
public class AddOperationAction : IConfigureServicesAction
    {
        public int Priority => 1000;
        public void Execute(IServiceCollection services, IServiceProvider serviceProvider)
        {
            DependencyResolver.Init(serviceProvider);
            services.AddScoped<IOperation, PlusOperation>();

I insert this instruction:
            IOperation iOperation = ExtensionManager.GetInstance<IOperation>();
the variable iOperation give one implementation of one operation (and not null)

but, if I try to use this instructions: with .addSingleton()

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            HttpContextAccessor iHttpContextAccessor = ExtensionManager.GetInstance<HttpContextAccessor>();

the variable iHttpContextAccessor  give null   !!!!!!!!!!

what is the problem?

how can I use a Singleton class with .addSingleton and retrieve by ExtensionManager? or there are other methods to solve this problem????

Thanks for all.

**Comment by DmitrySikorsky** [comment]
So, first of all, `ExtensionManager` class is not designed to get the services from the DI. Please just inject needed service in a constructor as usual or get it using the IServiceProvider.

What ExtensionManager.GetInstance() method does is just looks inside all the assemblies for the implementation of some interface and instantiates it. If a type doesn't have a constructor with no parameters instantiation will fail unless you pass constructor parameters explicitly.

**Comment by niconico49** [comment]
Ok, thanks for the pearl of wisdow.
