### ISSUE TITLE
Access to embeded resource of another extension in runtime

### ISSUE THREAD

**Issue by ErcinDedeoglu** [ExtCore/ExtCore#113]
I would like to access to an embeded resource from another extension. Is that possible? And how?

Detail: I'll put .sql files, they will create database. Each extension will have their own sql files. At runtime, I'll combine them and execute.

**Comment by Xarkam** [comment]
Hello, simply give the embeded resource path.
In embeded ressource, path OS separator become a `.` and `-` become a `_`

Here, I give embeded resource path https://github.com/SOFTINUX/Base/blob/master/Security/Views/GrantPermissions/Index.cshtml#L12

**Comment by ErcinDedeoglu** [comment]
I mean,

Structure:
WebApplication (Get embeded resource of ExtensionA from here)
WebApplication.ExtensionA (Set embeded resource)

When I try to get a sql file which is embeded resource of ExtensionA from Main application (WebApplication)

Executing this line only gives me embeded resources of WebApplication.
string[] resourceNames = Assembly.GetExecutingAssembly().GetManifestResourceNames();
But I want to reach Extensions too.

**Comment by Xarkam** [comment]
I do not understand the problem very well.
In my example, the line loads a resource located in Barebone extension from the Security extension.

You can always help you https://github.com/0xd4d/dnSpy to explore your extensions dll if you need.

**Comment by DmitrySikorsky** [comment]
@ErcinDedeoglu you can use my methods for resources manipulation (I'm going to write a post to my blog about that):

```
public static string GetResourceString(string resourceName)
    {
      using (Stream resourceStream = typeof(ResourceManager).Assembly.GetManifestResourceStream(resourceName))
        using (StreamReader reader = new StreamReader(resourceStream, Encoding.UTF8))
          return reader.ReadToEnd();
    }

    public static void WriteResourceToFile(string resourceName, string destinationPath)
    {
      using (Stream resourceStream = typeof(ResourceManager).Assembly.GetManifestResourceStream(resourceName))
        using (FileStream fileStream = System.IO.File.Create(destinationPath))
          resourceStream.CopyTo(fileStream);
    }
```
