### ISSUE TITLE
How to share EFCore DbContext from master to extensions?

### ISSUE THREAD

**Issue by ErcinDedeoglu** [ExtCore/ExtCore#114]
I saw #89 and http://docs.extcore.net/en/latest/getting_started/using_migrations.html
I done it, but i couldn't use DbContext for sql server.
I tried to select row from database in an extension but no success. Is there a clean sample project?
Thanks advance.

**Comment by DmitrySikorsky** [comment]
Yes, please take a look at https://github.com/ExtCore/ExtCore-Sample-Accounting

It has 3 extensions, 2 of them have their own entities which are registered inside the single db context.

**Comment by ErcinDedeoglu** [comment]
I'll try it. Also I would like to store DbContext, Migration files and connection string in an  extension. And other extensions will take db setting from main extension. Is that possible? 

Structure:
WebApplication (ExtCore)
WebApplication.Extension.A (Database settings + Migrations)
WebApplication.Extension.B (only use db from A)
WebApplication.Extension.C (only use db from A)

Thanks advance.

**Comment by DmitrySikorsky** [comment]
I'm not sure I  understand your question.

While ExtCore-based web apps can support different DB types implementations at the same time, having Abstractions layer for repositories is recommended. Example:

https://github.com/Platformus/Platformus/tree/master/src/Platformus.Domain.Data.Abstractions

Then, implement this interfaces in as many projects, as many DB types your application supports. Example:

https://github.com/Platformus/Platformus/tree/master/src/Platformus.Domain.Data.EntityFramework.SqlServer
https://github.com/Platformus/Platformus/tree/master/src/Platformus.Domain.Data.EntityFramework.Sqlite
https://github.com/Platformus/Platformus/tree/master/src/Platformus.Domain.Data.EntityFramework.PostgreSql

Then, just use abstractions everywhere, without thinking about current DB type implementation. Current DB type implementation is only specified by choosing corresponding DB implementation assembly. If you include ...SqlServer.dll (or project, or NuGet reference) to your main web application, it will use SqlServer as DB type. If you prefer SQLite - just include it. The only change you have to make is specifying correct connection string.


Your extensions can use data layer of another ones. But they only should rely on abstractions,  not on implementations. Example (Platformus.Domain extension uses Platformus.Globalization one):

https://github.com/Platformus/Platformus/blob/master/src/Platformus.Domain.Data.Entities/Platformus.Domain.Data.Entities.csproj#L16

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please, feel free to reopen it if you have any additional questions or information.
