### ISSUE TITLE
How to understand all extensions loaded?

### ISSUE THREAD

**Issue by ErcinDedeoglu** [ExtCore/ExtCore#115]
I would like to fire an event on main WebApplication after all extensions loaded successfully? Is it possible?

**Comment by DmitrySikorsky** [comment]
Hm, AddExtCore (and UseExtCore as well) extension method is synchronous, so next line of code after it might be considered as fact that all the extensions were discovered and loaded. Or you want more control over that?

**Comment by ErcinDedeoglu** [comment]
It's quite enough to for my solution. Thank you.
