### ISSUE TITLE
How can I invoke a method in Extension from WebApplication?

### ISSUE THREAD

**Issue by ErcinDedeoglu** [ExtCore/ExtCore#116]
I would like to invoke a method inside an extension from WebApplication. Is it possible?
WebApplication => Startup
     public void ConfigureServices(IServiceCollection services)
     {
            services.AddExtCore(this._extensionsPath);
            //here i want to call a method in ExtensionA:
            //like:
            ExtensionA.Test();
     }

possible?
:)

Thanks advance.

**Comment by DmitrySikorsky** [comment]
Hi! First of all, there is no such thing like 'method of the extension'. You can define some interface like IMathFunction with Calc method in it with 2 args: a and b. This method will return result of math operation.

Then you can implement that interface twice and put the implementations in 2 different assemblies. Then you can load one of them (for example, by putting it to the extensions folder) and then get existing implementation of the IMathFunction using ExtCore's ExtensionManager class.

Example: https://github.com/ExtCore/ExtCore-Sample-Service

You can define some IExtension interface and implement it in every extension. Then you will be able to get all the implementations and provide some actions with them.

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please, feel free to reopen it if you have any additional questions or information.
