### ISSUE TITLE
Solution with TagHelper declared in one External Project

### ISSUE THREAD

**Issue by niconico49** [ExtCore/ExtCore#117]
Hi
Can you provide a sample using custom Taghelper defined and used in a external class library / project?
For instance: create 1 solution with 2 projects:

1) with only the Program.cs and the Startup.cs
2) with UseMvcAction, Index.cshtml, and a Custom Taghelper used, for example by the same Index.cshtml

thanks and good work!!!!

**Comment by DmitrySikorsky** [comment]
Hi! Yes, it is possible:

Project with tag helpers: https://github.com/Platformus/Platformus/tree/master/src/Platformus.Barebone.Backend/Areas/Backend/TagHelpers/Fields

Another project that uses them:
https://github.com/Platformus/Platformus/blob/master/src/Platformus.Menus.Backend/Areas/Backend/Views/Menus/CreateOrEdit.cshtml#L13

**Comment by niconico49** [comment]
Thanks!
