### ISSUE TITLE
Pointing to Views path with WebRootFileProvider 

### ISSUE THREAD

**Issue by ErcinDedeoglu** [ExtCore/ExtCore#118]
I'm trying to prepare a development environment for team work.
But every changes on the project need rebuild.
So I'm trying to find a solution with WebRootFileProvider.
I want to run it only on #DEBUG stage, so PROD will be standard.

I solved css, javascript files with the following code:

```
IFileProvider[] fileProviders = {
new PhysicalFileProvider(@"C:\Users\edede\Desktop\Core Tests\X1\WebApplication\Extension.Alpha"),
new PhysicalFileProvider(@"C:\Users\edede\Desktop\Core Tests\X1\WebApplication\WebApplication"),
hostingEnvironment.WebRootFileProvider
};
hostingEnvironment.WebRootFileProvider = new CompositeFileProvider(fileProviders);
```

**But views (.cshtml) not affecting.**
When I change something inside a view (.cshtml) it's not showing up without rebuild.

Is there a solution for this? This is the most important part for us.
Thanks advance.

**Comment by DmitrySikorsky** [comment]
Good question. I think it is not enough just to add one more file provider. I think we also need to extend view locator.

This is one of the features I want to add in the future releases. To make it possible to work with static content without rebuild on development mode.

**Comment by Xarkam** [comment]
All cshtml file need to be compiled.
You need just in time compilation for cshtml: https://stackoverflow.com/a/24968741

But, the razor pages is inclued into dll. 
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-2.0&tabs=aspnetcore20

I will see with my wife if she has an idea on the subject.

**Comment by ErcinDedeoglu** [comment]
I solved it with writing a handler.
In my example:

I added this helper class: (In my example I store Extension projects inside the WebApplication project because MVC View cannot locate parent folder of the MVC project)

```
    public class ViewHelper
    {
        public static ViewResult ViewResult(ViewResult viewResult, ControllerContext controllerContext, string contentType = "text/html")
        {
#if DEBUG
            viewResult = new ViewResult()
            {
                ContentType = contentType,
                ViewName = string.Format("~/_Extension/{0}/Views/{1}/{2}.cshtml",
                    System.Reflection.Assembly.GetCallingAssembly().GetName().Name,
                    controllerContext.ActionDescriptor.ControllerName,
                    controllerContext.ActionDescriptor.ActionName)
            };
#endif
            return viewResult;
        }

        public static string LayoutPathHandler(string layoutPath)
        {
#if DEBUG
            layoutPath = layoutPath.Replace("~/_Extension/Extension." + RegexHelper.Between(layoutPath, "~/_Extension/Extension.", "/Views/"), "~");
#endif

            return layoutPath;
        }
    }
```

I implemented my method on return line of action:
```
        public ActionResult Index()
        {
            return Helper.ViewHelper.ViewResult(this.View(), this.ControllerContext);
        }
```
Also Layout must be
```
@{
    this.Layout = Extension.Helper.ViewHelper.LayoutPathHandler("~/_Extension/Extension.Alpha/Views/_Shared/_AlphaLayout.cshtml");
}
```

I know this is not best practice. But you can find an exit point. :)
I think @DmitrySikorsky will kill me because of this :)

**Comment by Xarkam** [comment]
@DmitrySikorsky for static files js/css I use webroot (https://github.com/SOFTINUX/Base/blob/master/WebApplication/Program.cs#L19)
Personally, I find this way of doing things more practical.

**Comment by irowbin** [comment]
@DmitrySikorsky This is what i was looking for since beta channel. 🤣😅🤗

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please feel free to reopen it any moment if you have any additional question or information.

**Comment by Kharabet** [comment]
@DmitrySikorsky Hi,
Will you add this functionality to the newer versions? This is very useful when developing applications with complicated html markup.

**Comment by DmitrySikorsky** [comment]
I'm going to review the way ExtCore works with the static files and views, so I will try to make it possible.
