### ISSUE TITLE
Link 2 link for Razor pages inside external module

### ISSUE THREAD

**Issue by niconico49** [ExtCore/ExtCore#119]
Hi,
this time I have this problem:
how can I link a .cshtml page inside the "<a href" of another .cshtml page?

for instance.... normally the extcore launch some class like UseMvcAction that make route for call an Index.cshtml pages:
 routeBuilder.MapRoute(name: "Default", template: "{controller=Default}/{action=Index}");
 that call:

    public class DefaultController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }

and the view is (in this case) inside Views/Default/Index.cshtml

the question is:

if I have another page MyRazorPage.cshtml inside some other directory (for instance Pages/MyRazorPage.cshtml), then what kind of settings and what I have to write inside some tag "< href="????" in the Index.cshtml pages?

And, over the top, because I will make a lot of RazorPage.cshtml inside the Pages directory and eventually some subdirectory, is there a simple url to write inside "<a href" like the question before, or is too complex to manage??  Can you help me and give some pearls of wisdom?? Thanks.

**Comment by DmitrySikorsky** [comment]
Hi! I need to test how to deal with razor pages from different extensions. Then I will answer.

**Comment by Xarkam** [comment]
Hello,

you have to put the `route/viewname` in the href

All is made by route to localize view.

You can give a route to the controller as in this example: https://github.com/SOFTINUX/Base/blob/master/SeedDatabase/Controllers/SeedDatabaseController.cs#L42
(this example call a controller to execute it)

Look at https://stackoverflow.com/questions/41908957/get-all-registered-routes-in-asp-net-core for more explaination on routes

**Comment by Xarkam** [comment]
Hello,

you have to put the route/viewname in the href

All is made by route to get view.

You can give a route to the controller as in this example: https://github.com/SOFTINUX/Base/blob/master/SeedDatabase/Controllers/SeedDatabaseController.cs#L42
(this example call a controller to execute it)

Look at https://stackoverflow.com/questions/41908957/get-all-registered-routes-in-asp-net-core for more explaination on routes

Also see `@Html.RenderAction`, `@Html.Raw(Url.Action())` in ASP.NET Core documentation.

**Comment by niconico49** [comment]
thanks Xarman but your solution is the same as the DefautlController and Index.cshtml…. because you have defined the route like annotation in the method and have used the function Ok() instead of View....

but my question was a little different: is possible to have "<a href="????"> Directly linked to another page.cshtml, without the implementation of some class controller. Normally in netcore webapplication project and without external library like extcore, is possible to call and link directly the .cshtml page (without controller implementation), but do you know the same solution in extcore (obviously with the definition of the .cshtml file/class/razor page in external library/.dll????

Thanks for help, bye!!!!

**Comment by postb99** [comment]
As far as I know, any request should always be processed by a controller before going to a target view, and this works the same with or without extcore. So your url/route corresponds to some controller's method.

**Comment by Xarkam** [comment]
Ok, and with `@Page` directive as mentioned here: https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/?view=aspnetcore-2.0&tabs=visual-studio#razor-pages ?

Take attention to the associations of URL table.

I guess the solution lies in the path of the page to put in the href

**Comment by niconico49** [comment]
The @page attribute infact avoid the use of the controller but the problem remains,
how to do the mapRoute settings to instruct the extcore to open ours razor .cshtml page

for example:

with this Index.cshtml inside the Pages directory:
Pages/Index.cshtml:

@page
<h1>Pages/Index</h1>

how can I define the mapRoute method (if is the right thing to do, obviously)?
            //routeBuilder.MapRoute(name: "Default", template: "{controller}/{action}", defaults: new { controller = "Barebone", action = "Index" });

**Comment by niconico49** [comment]
Finally, I have Solved Myself, Thanks.

**Comment by Xarkam** [comment]
Please @niconico49 share your solution ;)

**Comment by tb-mtg** [comment]
@niconico49  yes please share how you did it
