### ISSUE TITLE
Razor support in Pages directory for extcore (netcore 2.0)

### ISSUE THREAD

**Issue by niconico49** [ExtCore/ExtCore#120]
Actually extcore support the feature of the netcore 2.0 but in the "original" MVC format where, normally there are 3 elements for every page (Actions, Controllers and Views), but, on the other hand, netcore 2.0 have the razor pages, inside the Pages directory, support too.

Is possible to have support for razor pages in extcore too?

thanks, and good jobs!!!!

**Comment by ErcinDedeoglu** [comment]
Hi @niconico49 
As far as I know razor pages are supported. I didn't understand what you mean with "Pages directory". Could you explain it please (or link)

Also could you upload a simple project about your mean?

**Comment by niconico49** [comment]
if you use Pages directory inside the WebApplication projects of an ExtCore solution, ok ….. no problems

but if you try to add Pages directory inside an external project called, for example RazorExt with a simple Index.cshml page (Pages\Index.cshtml) with something like:

@page
< h1>Index Page< /h1>

and then have this kind of structure:
Solution.sln
RazorExt.csProj
Pages\Index.cshtml
….other file .json etc.
WebApplication.csProj
\External\RazorExt.dll (dll of RazorExt project compiled and copie here)
….other file .json etc.

how can you arrive to Index.cshtml without use the UseMvcAction class?

remebre that in every Sample project of the Extcore there are this structure:
Actions\UseMvcAction.cs
Controller\DefaultController.cs
Views\ and Views\Shared with Index.cshtml

but in Razor case the only page is
Pages\Index.cshtml in this very simple explanation

So the question, how can I arrive to Razor Pages\Index.cshml inside an external project / dll instead of WebApplication?, (obviously without the use of the Action/Controller class thanks to annotation @page.

**Comment by niconico49** [comment]
Finally I have Solved by myself, thanks!!

**Comment by tb-mtg** [comment]
@niconico49 how did you solve this as i would also like to do something similar.

**Comment by DmitrySikorsky** [comment]
@niconico49 please, share your solution, it can be helpful for the others.

**Comment by jefrisibarani** [comment]
@niconico49, please share your solution.
Thankyou

**Comment by dotfelixb** [comment]
If this is still relevant let me know, I got it to work for Razor pages as described above

**Comment by tb-mtg** [comment]
@dotfelixb I'm interested in seeing how you got it to work

**Comment by dotfelixb** [comment]
> @dotfelixb I'm interested in seeing how you got it to work

You can find the link to the example project [here](https://github.com/dotfelixb/WebExtCorePages)

on standby for any questions.
