### ISSUE TITLE
ExtCore vs Application Parts

### ISSUE THREAD

**Issue by ErcinDedeoglu** [ExtCore/ExtCore#121]
Why should we use ExtCore when we have Application Parts?
What does ExtCore provide?
What are the main reasons for choosing ExtCore when comparing two?

I need to share this knowledge with my company developers.

Info: https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.0

**Comment by DmitrySikorsky** [comment]
Hi! Thank you for the question. As you can see here

https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.Mvc/Actions/AddMvcAction.cs#L41

ExtCore uses application parts feature, but that feature solves small piece of the task. It helps to resolve controllers, view components, and tag helpers from the specified assemblies.

But ExtCore's task is more complex. It allows to discover and load assemblies, to resolve controllers, view components, tag helpers, views, static content (CSS, JS, images and so on). It also contain features to resolve types and instances among the loaded assemblies, to notify subscribers with events, to build data context from the entities from the different extensions etc. So it is  full-features solution for building modular applications, while application parts feature only allows to use controllers/view components/tag helpers from the specified assembly.

**Comment by ErcinDedeoglu** [comment]
The answer was delivered. Thank you so much.
