### ISSUE TITLE
Up to net core 2.1

### ISSUE THREAD

**Issue by KANekT** [ExtCore/ExtCore#122]
Pleaze app all defenitions to net core 2.1

**Comment by Xarkam** [comment]
I do not think this is a good idea until the final version is released :)

**Comment by KANekT** [comment]
@Xarkam 
https://www.nuget.org/packages/Microsoft.AspNetCore/2.1.0

**Comment by Xarkam** [comment]
Ho, yes you are right we are the 30th of May :)

**Comment by DmitrySikorsky** [comment]
Hi! I will try to move to 2.1 this weekend.

**Comment by DmitrySikorsky** [comment]
Done: https://github.com/ExtCore/ExtCore/releases/tag/3.3.0-beta1
