### ISSUE TITLE
Question about security considerations

### ISSUE THREAD

**Issue by NickCullen** [ExtCore/ExtCore#124]
Hello,

I've been looking into  plugin architectures for a web app and came across this library which looks good! 

The project I have in mind would require eacg plugin to have it's own settings file as an encrypted embedded resource and have it so only the owning assembly can decrypt said file. 

My question is, can plugins have their own individual configuration settings and if so what have you done / (possibly) planning to do to restrict access from other plugins viewing these settings?

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please feel free to reopen it any moment if you have any additional question or information.
