### ISSUE TITLE
Problems using SQL Server 2005

### ISSUE THREAD

**Issue by bacellijulian** [ExtCore/ExtCore#132]
Hello Dmitry, i'm having some troubles while using sql server 2005, is there any way to configure ef core to run with this version? I tried a lot of things and can't find where to do it.
I would like to be able to specify the provider as SQL Server 2005, is it posible?
Thanks in advance!
@DmitrySikorsky

**Comment by DmitrySikorsky** [comment]
Hi! It seems EF Core doesn't support MS SQL Server 2005: https://stackoverflow.com/questions/39505664/error-asp-net-core-ef-core-and-sql-server-2005-the-version-of-sql-server-in-use
