### ISSUE TITLE
Need to start a transaction through Storage

### ISSUE THREAD

**Issue by bacellijulian** [ExtCore/ExtCore#133]
Hi, I need to replace the default IStorage and Storage to be able to add the event BeginTransaction and CommitTransaction there.
Is it posible to inject my own class?

**Comment by DmitrySikorsky** [comment]
Yes, sure. Or you can just cast IStorageContext to your real context type (DbContext in case of EF) and call corresponding methods to work with transactions.

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please feel free to reopen it any moment if you have any additional question or information.
