### ISSUE TITLE
Using Options Pattern When Using Entity Framework Identity For IConfigurationBuilder?

### ISSUE THREAD

**Issue by YodasMyDad** [ExtCore/ExtCore#138]
I am trying to setup Entity Framework Identity in a project and have been following your Identity example on here. However, within the `ConfigureServicesAction` where you set the DbContext and AddIdentity method. 

To get the `IConfigurationBuilder` class, you have a comment above it

`// This is a bad (but quick) way to provide configurations to the extensions. A good one is to use the options pattern.`

**What is the options pattern?** How can I find out more about it, or even better see an example of using it? I have looked through all your ExtCore samples and cannot see an examples of it?

**Comment by Xarkam** [comment]
Hello

look this https://github.com/SOFTINUX/Base/blob/master/WebApplication/Startup.cs We using the options pattern.

Documentation about https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1

**Comment by YodasMyDad** [comment]
Thanks. I was going by the Identity example and it was setting up Identity and the Context in an extension and not the Web Application root (Which is where I had it initially!!). 

I'll move everything back to how I was using it. Love your base project too. That's a great reference for me now. Thanks again for your help.

**Comment by YodasMyDad** [comment]
Actually. Is there a way to use the options pattern but from an Extension? The examples shown by @Xarkam have Identity and the application context registered in the root web application. Ideally this all needs to be done via an extension to be able to keep the app fully modular. Like this original Identity sample/example.

**Comment by DmitrySikorsky** [comment]
@YodasMyDad I think that while options setup is done inside the ConfigureServices, you can use ExtCore's IConfigureServicesAction interface for that with no problems.

**Comment by YodasMyDad** [comment]
Thanks, I'll give that a go.
