### ISSUE TITLE
Question: Is ExtCore suitable for this type of extensible ASP.NET Core applications

### ISSUE THREAD

**Issue by montyclt** [ExtCore/ExtCore#139]
Original question: https://stackoverflow.com/questions/52486566/extensible-asp-net-core-2-application

> I need to create an ASP.NET Core 2 application that can be extensible.
> 
> An extension, is a project that reference the main assembly and can extends it adding new controllers, models (with EF migrations), views, razor pages, etc.
> 
> Because the extensions need use the main application base classes like base controller, base model or view/page layout, the main application cannot reference the module project (avoid circular references).
> 
> I'm not sure how can I achieve this, but the idea is an installation of the main project, can add new functionality simple putting the modules DLL (or by online market in the main application, that download the DLL).
> 
> In my research, I found [Applications parts](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.1), but my problem here is I need specify the part assembly in Startup class, and I need in installed the capacity of install modules without doing any changes in the code.
> 
> Some modules, need be extensible too, for example, an accounting module, need to connect with bank, and it have an interface that defines the methods of working with the bank, for example:
> 
> ```
> public interface IBankingOperation
> {
>     public async void PayInvoiceAsync(Invoice invoice);
>     // More methods...
> }
> ```
> Then, differents projects can reference the banking assembly and provide implementation for differents banks. Thats means a module need register interfaces in the DI Container.
> 
> In the main application, this modules can be installed like other modules, but checking the base module is intalled, for example, I can install the Santander module like other module, but only if banking module is installed (module dependency).
> 
> **In conclusion**, I need to create a modular ASP.NET Core 2 application, but the main assembly cannot reference the modules, the modules must reference the main assembly. The modules can contain Controllers, Models, Views, Pages, Etc.

Is ExtCore suitable for this issue? Thank you!

**Comment by Xarkam** [comment]
Hello @montyclt 

Yes Extcore can help you to implement in your application, the flexibility application part.
But, .Net Core, does not allow to hot load/unload assembly.

You can see https://github.com/Platformus/Platformus or https://github.com/SOFTINUX/Base to show how make this

**Comment by montyclt** [comment]
Hello @Xarkam 

Thanks for the examples, the source code really help me on my project.

I have a question, you said .NET Core does not allow to hot load or unload assembly, but can I restart the web server after installing an extension from my application?

**Comment by Xarkam** [comment]
Absolutely yes :)

And, same if you would remove extension, you must stop server before remove it.

**Comment by montyclt** [comment]
@Xarkam Thank you!
