### ISSUE TITLE
Unable to resolve service for type 'ExtCore.Data.Abstractions.IStorage'

### ISSUE THREAD

**Issue by FabianJaenicke** [ExtCore/ExtCore#140]
Hi,
First of all, you have created a very interesting and clever library with ExtCore.
I'm implementing a dashboard with ExtCore and I've been mostly based on your examples so far.
Now I was ready to use a SQLite database. But unfortunately I don't get an IStorage instance from the Dependency injection with your example extensions or with my own extension.
When I try this I always get the following exception: ```System.InvalidOperationException: Unable to resolve service for type 'ExtCore.Data.Abstractions.IStorage' while attempting to activate 'Extension.Controllers.DefaultController'```
Do I have to register an instance or somethink like that?

**Comment by Xarkam** [comment]
Hello, look at https://github.com/SOFTINUX/Base/blob/master/src/SoftinuxBase.WebApplication/Startup.cs#L113 
You must activate by add line 112 & 113, we have added registration for dependencies injection.

**Comment by DmitrySikorsky** [comment]
Hi @FabianJaenicke ! I think you haven't added dependency on ExtCore's implementation for SQLite. Like this: https://github.com/ExtCore/ExtCore-Sample-Data/blob/master/src/WebApplication/WebApplication.csproj#L10

Everywhere in your app you just work with a storage using the abstraction. But you have to tell your app which implementation to use by including corresponding NuGet package (or a DLL file).

**Comment by FabianJaenicke** [comment]
Thank you both. Unfortunately your solution didn't work, but in the meantime I found the problem. I had no reference to the implementation of my repositories in my web project. 
@Xarkam @DmitrySikorsky

**Comment by FabianJaenicke** [comment]
But is it also possible to get an IStorage instance in a class wich does not inherit from Controller?
Because i whant my Data accsess in a Service Class, not direktly in the Controller.

**Comment by postb99** [comment]
By convention the dependency injection always "starts" from controllers so your service class should be called from a controller that is then able to pass it all what it needs.

**Comment by FabianJaenicke** [comment]
Ok makes sense, but I'm looking for a way to write something to the database once, when the application starts. Does anyone have a suggestion how this can be done?

**Comment by DmitrySikorsky** [comment]
You can get the instance any time after it is registered. You can use GetService method of the service provider.

**Comment by DmitrySikorsky** [comment]
As I see, the problem is that SettingsManager needs implementation of the ISettingsRepository and can't find it. I think you didn't register it in the DI. You only register there your setting manager.

ExtCore itself doesn't use DI to inject repositories, it finds for the implementations using the ExtensionManager, just looks for the implementation between the available types.

So if you want to inject repository to your setting manager you have to register the implementation of the ISettingsRepository in the DI too.

**Comment by FabianJaenicke** [comment]
Thanks for your answer. In principle, that was the problem. But when I added a SettingsRepository to the DI, the instance that i got in the SettingsManager had no storage context set.
Like that:
```C#
serviceCollection.AddScoped(typeof(ISettingsRepository), typeof(SettingsRepository));
```
My solution for that is: I created my own implementation of IStorageContext. Then I created an instance of SettingsRepository in a IConfigureServicesAction and registered it as a singletone in DI. 
Now the IStorageContext is set when DI passes an instance of ISettingsRepository into the SettingsManager.

```C#
public class ConfigureRepositorieAction : IConfigureServicesAction
{
     public void Execute(IServiceCollection serviceCollection, IServiceProvider serviceProvider)
     {
         var context = new MyStorageContext(Settings.Default.SettingsDB);
         var settingsRepository = new SettingsRepository(context);
         serviceCollection.AddSingleton(typeof(ISettingsRepository), settingsRepository);
     }

     public int Priority => 20;
}

public class MyStorageContext : IStorageContext
{
    public string ConnectionString { get; private set; }

    public MyStorageContext(string connectionString)
    {
        this.ConnectionString = connectionString;
    }
}

```

**Comment by erbpsy** [comment]
Add services.AddSingleton<IEmployee, EmployeesMockup>(); in your ConfigureServices method of Startup.cs file of your project.

 public void ConfigureServices(IServiceCollection services)
	{
		services.AddRazorPages();
		// To register interface with its concrite type
		services.AddSingleton<IEmployee, EmployeesMockup>();
	}
For More details please visit this URL : https://www.youtube.com/watch?v=aMjiiWtfj2M

for All methods (i.e. AddSingleton vs AddScoped vs AddTransient) Please visit this URL: https://www.youtube.com/watch?v=v6Nr7Zman_Y&list=PL6n9fhu94yhVkdrusLaQsfERmL_Jh4XmU&index=44)

**Comment by ngouz** [comment]
> Thanks for your answer. In principle, that was the problem. But when I added a SettingsRepository to the DI, the instance that i got in the SettingsManager had no storage context set.
> Like that:
> 
> ```cs
> serviceCollection.AddScoped(typeof(ISettingsRepository), typeof(SettingsRepository));
> ```
> 
> My solution for that is: I created my own implementation of IStorageContext. Then I created an instance of SettingsRepository in a IConfigureServicesAction and registered it as a singletone in DI.
> Now the IStorageContext is set when DI passes an instance of ISettingsRepository into the SettingsManager.
> 
> ```cs
> public class ConfigureRepositorieAction : IConfigureServicesAction
> {
>      public void Execute(IServiceCollection serviceCollection, IServiceProvider serviceProvider)
>      {
>          var context = new MyStorageContext(Settings.Default.SettingsDB);
>          var settingsRepository = new SettingsRepository(context);
>          serviceCollection.AddSingleton(typeof(ISettingsRepository), settingsRepository);
>      }
> 
>      public int Priority => 20;
> }
> 
> public class MyStorageContext : IStorageContext
> {
>     public string ConnectionString { get; private set; }
> 
>     public MyStorageContext(string connectionString)
>     {
>         this.ConnectionString = connectionString;
>     }
> }
> ```



> Yes... And that's because storage context is not injected inside the repository, but set by SetStorageContext method. I think it is not the best idea. I even have issue for that: #38
> 
> So, I think ExtCore.Data should register all the repositories as the services inside the DI. So users will be able to inject them directly, while I suggest to use repositories only using the IStorage to follow the Unit of Work pattern.

Hi, 
i've been working on Extcore lately and quiet frankly i'm still learning how to code in asp net core. i got some issue when am using the DI. I've read you guys talking about the new feature like DesignTimeStorageContextFactory. Is that something that has to do with the DI ? would you mind telling me how to avoid this error "Constructor on type 'blah blah' not found" when am calling the class that uses the DI (IStorage) ? i'll really appreciate it.
