### ISSUE TITLE
How to store migrations in extension?

### ISSUE THREAD

**Issue by montyclt** [ExtCore/ExtCore#141]
Hello!

I followed the migration tutorial, and now I have a mechanism to create migrations, but all migrations are stored in the same assembly.

In my application, I have two main projects:

- The `Base` project where is DbContext, important entities and interfaces for extending.
- The `Core` project that have Program and Startup, and my own AssemblyProvider implementation.

An extension must reference base project and implement the extension interfaces, but I need some extension has it own database entities, some of this entities, with relationships with the base entities (achieve following the tutorial), and its migrations (didn't achieve).

My idea is some third party developers can develop extensions without doing any changes in core or base assembly, and in the first use of the extension, do some task like migrate database (and other posible task related with the extension).

Thank you!

**Comment by postb99** [comment]
Hi, we're on the road to do the same things, because, based on ExtCore, we created SoftinuxBase (https://github.com/SOFTINUX/Base). I'm just working on what you already succeeded to do (the Base and the Core projects), maybe can you share the basic structure of your projects and the ef commands you use? I don't have enough knowledge of EF to answer your question but am highly interested by it.

**Comment by montyclt** [comment]
Hello @postb99 

As I read, the Entity Framework team is working in a feauture planned for version 3.0.0. https://github.com/aspnet/EntityFrameworkCore/issues/2725

My structure is simple, I have a project named `Base` with all base clases like base controller, base entity, dbcontext, view layouts, etc.).

I have too a project named `Core` that contains the Program and the Startup classes, my assembly provider that loads extensions only if the extension is active (marked in database) and some core views like main dashboard or search view.

The next projects are extensions that have its actions (see ExtCore docs), controllers, pages, views, entities (for now, I store the migrations of all extensions in the `Base` project waiting the feauture in Entity Franework 3.0.0.0), etc.

**Comment by montyclt** [comment]
I close this issue until Entity Framework 3.0.0.0 release.
