### ISSUE TITLE
How to handle all exceptions (unhandled) with app.UseExceptionHandler

### ISSUE THREAD

**Issue by ErcinDedeoglu** [ExtCore/ExtCore#143]
Hi,
I would like to handle unhandled exceptions on app.UseExceptionHandler implementation; it can handle exception on main MVC project; but can't handle exception in Extensions. For example:
```
        public void Execute(IRouteBuilder routeBuilder, IServiceProvider serviceProvider)
        {
            object g = "dsadasd";
            int h = (int) g;
        }
```

This isn't firing the UseExceptionHandler's action. Could you advice me a exit point? Thanks advance.

**Comment by DmitrySikorsky** [comment]
So, I'm closing it for now, because it doesn't seem to be a ExtCore-related feature.
