### ISSUE TITLE
wwwroot content embedding

### ISSUE THREAD

**Issue by mitja-p** [ExtCore/ExtCore#146]
Any plans to provide support for ManifestEmbeddedFileProvider? I am having problems, because I want to embed wwwroot content, but that means that files are accessible via /wwwroot/js/... instead of just /js/

Or is there any better solution?

**Comment by mitja-p** [comment]
Found a workaround.

I used AddStaticFilesAction.cs from ExtCore and created a new IConfigureServicesAction with the following line modified 
`ExtensionManager.Assemblies.Select(a => new EmbeddedFileProvider(a, a.GetName().Name))`
to
`ExtensionManager.Assemblies.Where(a=>!a.GetName().Name.StartsWith("ExtCore")).Select(a => new EmbeddedFileProvider(a, a.GetName().Name+"."+"wwwroot"))`

I also excluded ExtCore libraries since they do not contain wwwroot.

**Comment by DmitrySikorsky** [comment]
Interesting. I think we are discussing similar things here: #99. You could join that discussion, so we could have a better solution.

**Comment by DmitrySikorsky** [comment]
So, this will be changed in #168. Please, write all the ideas there, so we could discuss the task.
