### ISSUE TITLE
TagHelpers from another project inaccessible inside extension

### ISSUE THREAD

**Issue by pathartl** [ExtCore/ExtCore#147]
Thanks for all the work on ExtCore, it's solving a large need that we have.

I'm running into an issue where I have the following projects inside my solution:

```
Application.UI
Application.Infrastructure
Application.Web
Application.Web.Extensions.Extension1
```

I believe I've matched the Platformus structure well, but I can't seem to use the tag helpers from `Application.UI` in the extension views. They do however work in the base `Application.Web` project's views. Extension1 does use areas (e.g. `Areas/TestArea`) and the extension has a `_ViewImports.cshtml` file that looks like:

```
@using Application.UI
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application.UI
```

Which mirrors the `_ViewImports.cshtml` from `Application.Web`. This is a .NET Core 2.1 app, which I was not sure if that had anything to do with it as Platformus is 2.0.

**Comment by DmitrySikorsky** [comment]
Hi! As you have mentioned, Platformus has no problems with such scenario.

A sample tag helper:
https://github.com/Platformus/Platformus/blob/master/src/Platformus.Barebone.Backend/Areas/Backend/TagHelpers/Fields/SingleLineTextFieldTagHelper.cs#L11

Its "registration" inside the same(!) assembly:
https://github.com/Platformus/Platformus/blob/master/src/Platformus.Barebone.Backend/Areas/Backend/Views/_ViewImports.cshtml#L6

And usage in another assembly:
https://github.com/Platformus/Platformus/blob/master/src/Platformus.Configurations.Backend/Areas/Backend/Views/Configurations/CreateOrEdit.cshtml#L13

Doesn't it work for you?

**Comment by pathartl** [comment]
Nope. What does seem to work, however, is adding the `@addTagHelper` directly inside the cshtml for the view

**Comment by DmitrySikorsky** [comment]
Have you added _VievImports to resources of the assembly with tag helpers?

**Comment by DmitrySikorsky** [comment]
...and in the extension project:
https://github.com/Platformus/Platformus/blob/master/src/Platformus.Configurations.Backend/Areas/Backend/Views/_ViewImports.cshtml

**Comment by DmitrySikorsky** [comment]
So, while I don't have any problems with that, I will close this issue for now.
