### ISSUE TITLE
Model of Extensions.dll not ofund

### ISSUE THREAD

**Issue by arwinf** [ExtCore/ExtCore#150]
Steps to reproduce;

1. Download mvc sample
2. Add new folder + model.cs file
3. try to use this model in view by using @model Extension.Models
4. receive an error, which says - namespace could not be found.

If I create a new library with name "Extensions.Models" I can use the view.

Can you explain, why? :o

**Comment by DmitrySikorsky** [comment]
Hi @arwinf! I'm sure there is some kind of typo or other mistake, because I use such scenario all the time with no problems.
