### ISSUE TITLE
Issue with full .Net Framework

### ISSUE THREAD

**Issue by EduVZ** [ExtCore/ExtCore#152]
Hi there.

I'm working through the tutorials and got stuck on the first one.
I've selected .Net Framework 4.6.2 for the WebApplication. I'm getting the following error when running the application:
"FileNotFoundException: Could not load file or assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

I've tried binding redirects but that is not solving the issue. The same setup with .New Core 2.2 for the WebApplication does work.

And I can't figure out why it's looking for version 4.0.0.0 of SYstem.Runtime.Loader when all the references seem to point to version 4.3.0.0.

Any help on this would be greatly appreciated.

Regards

Edu

**Comment by EduVZ** [comment]
Just stumbled onto this: https://github.com/dotnet/corefx/issues/22142.
So looks like System.Runtime.Loader is only for .Net Standard/Core and not for full framework.
Which seems to mean that while ExtCore depends on System.Runtime.Loader it will not be compatible with the full version of .Net.

**Comment by DmitrySikorsky** [comment]
Will look at this while working on 5.0.0 and moving to ASP.NET Core 3.
