### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type 't' while attempting to activate

### ISSUE THREAD

**Issue by abomadi** [ExtCore/ExtCore#153]
For some reason i keep having issue registering my service inside api controller in an extension
here is my setup
```
class ConfigureServices : IConfigureServicesAction
    {
        public int Priority => 1000;

        public void Execute(IServiceCollection serviceCollection, IServiceProvider serviceProvider)
        {
            serviceCollection.AddScoped(typeof(ITenantProvider), typeof(TenantProvider));
        }
    } 
```
```
public class TestController : Controller
    {
        private ITenantProvider _tenantProvider;
        public TestController(ITenantProvider tenantProvider)
        {
            this._tenantProvider = tenantProvider;
        }
```
if i remove the di from the controller everything works well in the main app. it looks like controller getting registered before registering the tenantprovider it self ? please advise @DmitrySikorsky

**Comment by DmitrySikorsky** [comment]
Hi,

I think the only reason of this issue is that your configure services action is not executed. Could you check in the logs, is it executed or not?
