### ISSUE TITLE
Razor not working correctly with directly referenced extensions

### ISSUE THREAD

**Issue by Kukks** [ExtCore/ExtCore#158]
I'm running into issues with the embedded views in plugins. I have a few plugins that I've been working on in my local dev environment with the main app directly referencing them. The Views and Scripts are all embedded in the plugins. Everything seems to load and work correctly but as soon as I publish a release(`dotnet publish` with the direct references intact), the mvc binding on any of these views/partials/viewcomponents seem to break. It's especially obvious with the form binding things (`asp-for` for example stay as is without generating the value or name or id attrs).
I've tried to debug by placing the following in one of the views:
```
<pre> @Html.Raw(JsonConvert.SerializeObject(ViewData.ModelState, Formatting.Indented))</pre>
<pre> @Html.Raw(JsonConvert.SerializeObject(Model, Formatting.Indented))</pre>
```
and it seems to work and actually print the correct data from Controllers & Models but any form binding helpers seem to be ignored completely such as the below:
```
<div class="form-group">
        <label asp-for="Server" class="control-label"></label>
        <input asp-for="Server" class="form-control"/>
        <span asp-validation-for="Server" class="text-danger"></span>
</div>
```
Any idea why? 

I'm also wondering what the process is to create plugins and distribute them. Would doing a dotnet publish be everything? I have plugins that use external nuget packages and full of Viewcomponents, partials, and controllers with views.

Repo is https://github.com/kukks/btctransmuter-vnext
Mentioned this here earlier:
https://gitter.im/ExtCore/ExtCore?at=5c841c2bc8e5bc5162143ca3

**Comment by rockstardev** [comment]
@DmitrySikorsky can you give any hints on where to look in codebase to start resolving this? Thanks!

**Comment by Kukks** [comment]
Ok, so issue had nothing to do with Extcore, it seems you need to add  `@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers ` to each independent plugin for the razor to function...
