### ISSUE TITLE
Extcore with core 3

### ISSUE THREAD

**Issue by niconico49** [ExtCore/ExtCore#159]
Do you have any intention to upgrade the extcore package for aspnetcore 3 ?

because now there is a big problem in this instruction:

            mvcBuilder.AddRazorOptions(
                o =>
                {
                    try
                    {
                        foreach (var assembly in ExtensionManager.Assemblies)
                            o.FileProviders.Add(new EmbeddedFileProvider(assembly, assembly.GetName().Name));
                    }
                    catch (Exception e)
                    {
                        var logger = serviceProvider.GetService<ILoggerFactory>().CreateLogger("ExtCore.Mvc");
                        logger.LogInformation("Executing AddRazorOptions'{0}'", e.Message);
                    }
                }
            );

especially in the o.FileProviders.Add(…

because in netcore 3 FileProvider List was removed form RazorViewEngineOptions class, and in you'll try to understand the source code from aspnetcore 2.* and aspnetcore 3.*, you'll find that the FileProviders List was moved inside other class like: MvcRazorRuntimeCompilationOptions, but, over the top, that class become internal class inside other internal class etc. and doesn't exist any public access to that List.

Do you have any intention to evolve the extcore for core 3.*, if, obviously, is possible?

Thanks and Good job!!!!

**Comment by Xarkam** [comment]
Hello, I think @DmitrySikorsky will upgrade to .Net Core 3 after released.

But, I think he will also maintain actual version to maintenance mode due to incompatibility with .net core 3.

**Comment by DanielS4n** [comment]
The support for collectible assemblies will also be implemented ?

This article talk about it, I tried it without ExtCore and it would be really important to develop applications with dynamic modules:
https://www.strathweb.com/2019/01/collectible-assemblies-in-net-core-3-0/

Thanks you!

**Comment by Xarkam** [comment]
Hello @DanielS4n ,
It will be necessary to wait @DmitrySikorsky for the answer at you question.

**Comment by DmitrySikorsky** [comment]
Hi @niconico49, @Xarkam , @DanielS4n. Thank you for your questions. Yes, I'm going to support and release new versions of ExtCore. Also, my team and I use it in our projects. But .NET Core is been developing fast, so I think I will have to review all the project and the idea itself to be sure that it still meets the requirements.
