### ISSUE TITLE
Load Dependencies

### ISSUE THREAD

**Issue by GVX111** [ExtCore/ExtCore#160]
In extension i can't load System.Private.ServiceModel
Loader doesnt loading all references.
FileNotFoundException: Could not load file or assembly 'System.Private.ServiceModel, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
I have added Connected Service and app can't load references correctly. How can i fix this issue?

**Comment by Xarkam** [comment]
Hello, does this issue reflect your context of use?
https://github.com/dotnet/wcf/issues/2349

**Comment by Flying--Dutchman** [comment]
Hello, 

I've got the same issue. But as it seems it is not related to dotnet/wcf#2349.
The missing file is: System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1.

But this file is present in the target directory.

I have updated to .NET Core 2.2, Updated Visual Studio and every nuget. but this problem still occurs. With this I'm unable to execute my code, let alone debug it.

**Comment by DmitrySikorsky** [comment]
Hi @GVX111. You either need to add explicit dependency on that package to your main web application project, or copy DLL file (and all its dependecies) to the extensions folder.
