### ISSUE TITLE
Not Registering entities (couldn't find IEntityRegistrar instances)

### ISSUE THREAD

**Issue by Nastya-Scherbakova** [ExtCore/ExtCore#161]
I added my projects as dependencies and use Sql Server and Identity. Architecture is like this
- API (dep to P1, P2 and Data) here is Context
- API.Data
- Plugin 1 (dep to Data) has EntityRegistrar
- Plugin 2 (dep to Data) has EntityRegistrar

Trying to register entities like this:
`this.RegisterEntities(modelBuilder);`

But nothing happened. Then I tried to check how many instances are there:
`var inst = ExtensionManager.GetInstances<IEntityRegistrar>(false);`
and got 0.

Why it couldn't find them?

**Comment by Xarkam** [comment]
Please @Nastya-Scherbakova , can you add your resolution ?
This could help in the future

Thanks.
