### ISSUE TITLE
Accessing Service from extension get different result

### ISSUE THREAD

**Issue by jefrisibarani** [ExtCore/ExtCore#162]
Hello,
I use CookieAuthentication in my main app.
When authenticated. i can access my user name 
 by injecting IHttpContextAccessor and accessing HttpContext.User  in my main app's view.

But this is not working in Extension's view.
I can inject IHttpContextAccessor , but i get differrent result( HttpContext.User is empty)

In short: Main app says user is authenticated, but in extension it is not authenticated.

How can i solve this?
Thanks in advance.

Jefri Sibarani

**Comment by postb99** [comment]
Did you register IHttpContextAccessor as singleton in your main app's Startup ? Your approach should work...

**Comment by Xarkam** [comment]
Hello, look at this https://github.com/SOFTINUX/Base/blob/master/src/Testing/Unit/CommonTest/DatabaseFixture.cs#L72
We registering `IHttpContextAccessor` in service.

**Comment by jefrisibarani** [comment]
> Did you register IHttpContextAccessor as singleton in your main app's Startup ?
Yes.

**Comment by Xarkam** [comment]
If @DmitrySikorsky does not answer by then, we'll see to make time next week to extend our project to test IHttpContextAccessor in an extension.

**Comment by DmitrySikorsky** [comment]
Hi @jefrisibarani, thank you for your question.

Are you registering `IHttpContextAccessor` in this way?

```
public class AddHttpContextAccessorAction : IConfigureServicesAction
  {
    public int Priority => 100;

    public void Execute(IServiceCollection services, IServiceProvider serviceProvider)
    {
      services.AddHttpContextAccessor();
    }
  }
```

I'm using such approach in different projects and it works without problems. Also, ExtCore doesn't have any special logic and doesn't process the services in any way, so if it works in "normal" ASP.NET Core app, it should work with ExtCore too.

**Comment by jefrisibarani** [comment]
Hi @DmitrySikorsky ,
Yes, already tried it, but the results are the same.
As a workaround, i put my authentication informations in another class,
then add it into IServiceCollection as a singleton.

Thank you.

**Comment by DmitrySikorsky** [comment]
So, I can only say that I'm using IHttpContextAccessor in the different ExtCore-based projects with no problems, so it must work.
