### ISSUE TITLE
Nested Layout 

### ISSUE THREAD

**Issue by cedriclange** [ExtCore/ExtCore#163]
Is there a way to nest a layout of the barebone _Layout in ExtensionA Layout.
The idea is that I want to achieve something like every extension can have it's menu navigations in the sidebar. Or is there a workaround?

**Comment by Xarkam** [comment]
Hello @cedriclange . Yes, we make this into https://github.com/SOFTINUX/Base

**Comment by cedriclange** [comment]
Hi @Xarkam , I was going through the docs of softinux . It's a great project, and that will be a shortcut to alot of things. Congrats for the project.
Let me get familiar with it I think I can jump from there.

**Comment by DmitrySikorsky** [comment]
I'm closing this issue for now, please feel free to reopen it any time if have additional questions.
