### ISSUE TITLE
Create new DB and migrate by code first

### ISSUE THREAD

**Issue by maka-dev** [ExtCore/ExtCore#166]
Hi Dmitry, 

I have sticked to your tutorial and have implemented the contextfactorys and when the DB exists getting the data is no problem. 

The Goal i have is, to create a new DB.sqlite at start (if file doesn't exist) and migrate (code-first) the tables to the new db. 

However when i try to execute "add-migration initalcreate" from efcore i get the exception
"No DbContext was found in assembly "ProjectName". 

Any Idea how i can solve this issue?

**Comment by DmitrySikorsky** [comment]
Hi @cma-cma, thank you for your question. So, migration works with the exising DB?
