### ISSUE TITLE
Enable/Disable Extension (from JSON File) Programmatically?

### ISSUE THREAD

**Issue by lrfahmi** [ExtCore/ExtCore#171]
I'm building a web API and using extcore as an extension manager. It's difficult to unload extensions at runtime. I tried writing enable / disable extension on json. How does the web api read the json extension's configuration, before the extension is executed?

If the extension is disabled, when accessing certain routes, the web api will respond that the extension is inactive.

Thank you.

**Comment by postb99** [comment]
Hi,

First, have a look at MVC's [ActionFilter](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.2).

Does this possible customization also interest you? https://extcore.readthedocs.io/en/latest/fundamentals/default_assembly_provider.html (@DmitrySikorsky the link to code is dead in the doc, here is one valid link to [DefaultAssemblyProvider](https://github.com/ExtCore/ExtCore/blob/5510ca0fff4a7594a2bdf2390bc9bb65f286874e/src/ExtCore.WebApplication/DefaultAssemblyProvider.cs)).
