### ISSUE TITLE
Add Extension While The Web Api is Running

### ISSUE THREAD

**Issue by lrfahmi** [ExtCore/ExtCore#172]
I have a api web project using .net core. Using ExtCore is very helpful for extensibility. I managed to make extensions with different dll projects. What if I want to add extensions (etc.) while the web api is running?

Thank you.

**Comment by lrfahmi** [comment]
In my opinion is **copying the new dll file** to the api web directory, **then restart the web api**. There are other ways besides these methods?

**Comment by Xarkam** [comment]
hi,
I do not know if this is possible because ExtCore scans the extensions folder for loading at startup.

I do not know the roadmap of version 5

**Comment by lrfahmi** [comment]
I'm trying to implement, Enable / Disable extensions in the webapp.

In the controller, my plan is to use ActionFilter, where ActionFilter will read the configuration (ex: extsettings.json), whether the extension is active or not.

Do you have feedback?

**Comment by DmitrySikorsky** [comment]
Hi @lrfahmi. We have #43 and #44. Now I'm updating my VS and I'm going to look at the .NET Core 3 and start fixing issues from ExtCore 5.0.0 milestone.

**Comment by DmitrySikorsky** [comment]
#43
