### ISSUE TITLE
Using core 3.0 AssemblyLoadContext to Implement Plug-in Hot Loading

### ISSUE THREAD

**Issue by ghd258** [ExtCore/ExtCore#173]
Using core 3.0 AssemblyLoadContext to Implement Plug-in Hot Loading

**Comment by lrfahmi** [comment]
Up. I need too. Load and unload at runtime.

**Comment by DmitrySikorsky** [comment]
I'm working on that. 2 problems now: how to invalidate view cache after application part is added at runtime and how to reconfigure endpoints and routes at runtime.

**Comment by DmitrySikorsky** [comment]
#43
