### ISSUE TITLE
The Web Application API does not work (404 error) after update to 5.0.0.0 version.

### ISSUE THREAD

**Issue by PeTrProduct** [ExtCore/ExtCore#174]

**Comment by PeTrProduct** [comment]
Не получается завести API контроллер (из примера), 404 ответ и никаких ошибок.

**Comment by DmitrySikorsky** [comment]
Да, я тоже воспроизвел эту проблема. Она возникает, когда сборки загружены как dll. Постараюсь с этим разобраться, буду благодарен за помощь.

**Comment by DmitrySikorsky** [comment]
Необходимо выполнить эту строку, чтобы маршруты из контроллеров заработали:
https://github.com/ExtCore/ExtCore-Sample-Api/blob/master/src/WebApplication/Actions/UseEndpointsAction.cs#L17
