### ISSUE TITLE
Load and unload plugins at runtime

### ISSUE THREAD

**Issue by Jantje2000** [ExtCore/ExtCore#176]
Hi, 

Currently I'm creating a multitenant app in .NET Core. With multitenant I mean an app which has a different database for each customer using it. Now I would add a plugin structure in my app too, but not every company which uses my software will use the same apps. Each request I should only load the plugins which that company needs, to prevent a bloat of features my customers don't use.

Is this possible when using ExtCore, that in a middleware, based on the current tenant, the plugins will be loaded?

**Comment by mattjcowan** [comment]
There's an interesting multi-tenant approach in OrchardCore where you can turn on different features (modules/extensions) all-together per tenant, and could also have different db connections too this way per-tenant, see: https://youtu.be/yrQaKv2mxFU?t=1420 ... Just adding to the discussion, would be cool to see this in ExtCore somehow

**Comment by DmitrySikorsky** [comment]
Hi! Thanks for the question. No, it is not possible and it won't be. I want to keep ExtCore very simple, but your case is rather specific (while I can fully understand why you need it).
