### ISSUE TITLE
IConfigureAction provided by ExtCore

### ISSUE THREAD

**Issue by postb99** [ExtCore/ExtCore#178]
Hello,

Why did you integrate the following `ApplicationBuilder `extensions as `IConfigureAction `into ExtCore ?
- `UseRouting()`
- `UseEndpoints()`

This causes issues because `UseAuthorization()` must appear between `UseRouting()` and `UseEndpoints()`, so the only way to get these three functionalities working is to implement `UseAuthorization()` through an `IConfigureAction`, with Priority between 10000 and 11000.

And this is not documented, I had to crawl ExtCore code to figure this out ;-)

So we have a suggestion: add an option to `UseExtCore()` to use or not these built-in `IConfigureAction`, because most of people prefer to have full control and clarity by putting everything in `Startup.cs`. An `IConfigureAction` lies somewhere in the project and can be missed.

We've started to setup a small repository to play with to reproduce the issue.

https://git.softinux.com/Xarkam/ExtCore-Sample-Accounting-With-Login

**Comment by DmitrySikorsky** [comment]
Hi @postb99!

I call UseEndpoints to make it simpler to register endpoints from the different extensions using the `IUseEndpointsAction`:

https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.Mvc/Actions/UseEndpointsAction.cs#L40

Priority is set to very big value (10000 and 11000), so it is easy to execute some code before these extension methods.
