### ISSUE TITLE
Blazor Support

### ISSUE THREAD

**Issue by weismantelf** [ExtCore/ExtCore#179]
Hello,

I like this framework very much. My question is, if I can also write extensions, which were 
using Blazor since Blazor is now avaialble in .net core 3.1?

thx

**Comment by DmitrySikorsky** [comment]
Hi @weismantelf, thank you for your question and for your interest. To be honest, I didn't try Blazor so far, but I think you can easily add its support just by writing some simple ConfigureServicesAction and ConfigureAction. Am I right?

**Comment by dotfelixb** [comment]
@weismantelf I can confirm Blazor works, is this still an issue for you?

**Comment by Xarkam** [comment]
Hello, see #183 
Thanks :)

**Comment by DmitrySikorsky** [comment]
Hi guys! While I still don't use Blazor, perhaps some of you who did try it could find some time to write few words in the docs to help others. It would be amazing. Also, I will appriciate any help with the ideas what should we do better for the Blazor users.

**Comment by YodasMyDad** [comment]
A sample project showing how you could use Blazor in Ext.Core modules would be great

**Comment by dotfelixb** [comment]
> A sample project showing how you could use Blazor in Ext.Core modules would be great

Check this [link](https://github.com/dotfelixb/WebExtCorePages) which shows Razor Pages Blazor support

**Comment by YodasMyDad** [comment]
Thanks I'll take a look

**Comment by DmitrySikorsky** [comment]
Thank you @dotfelixb! I will close this issue for now.
