### ISSUE TITLE
Update .net core 3.1

### ISSUE THREAD

**Issue by davidbuckleyni** [ExtCore/ExtCore#182]
Is there any plan to update this to .net core 3.1

**Comment by Xarkam** [comment]
Hello, I have created a pull request to update extcore to net core 3.1
https://github.com/ExtCore/ExtCore/pull/185

**Comment by dotfelixb** [comment]
Version 5.1 already target core 3.1

**Comment by Xarkam** [comment]
@dotfelixb yes and actually he made this warning on compilation if you don't have net core 2.1 installed:
```
 It was not possible to find any compatible framework version
  The framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
    - The following frameworks were found:
        3.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        3.1.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        3.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

5.1 it's compatibility version. With Net 5.0, we need to upgrade on full 3.1 before make specifical change of net 5.0

If you had taken the time to read my pull request, you would have seen the abandonment of netstandard.
As well as the adjustments specific to net 3.1

**Comment by DmitrySikorsky** [comment]
Hi guys, sorry for late answers, had no time to work on this project. Now I've updated ExtCore to use .NET 5.0. Please review the version 6.0.0 when have a chance. Should I remove the Microsoft.NETCore.App?

**Comment by DmitrySikorsky** [comment]
As I can see, we don't need that .netstandard2.0 anymore, net5.0 should replace everything: https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/

**Comment by Xarkam** [comment]
> Hi guys, sorry for late answers, had no time to work on this project. Now I've updated ExtCore to use .NET 5.0. Please review the version 6.0.0 when have a chance. Should I remove the Microsoft.NETCore.App?

I had removed it in my pull request. This is only there for .NET Core 3.0 and Netstandard 2.1. For Net Core 3.1 you must put in the project `<Project Sdk = "Microsoft.NET.Sdk.Web">
`
You must use this in net 5
