### ISSUE TITLE
Copy other dll to the plugins folder

### ISSUE THREAD

**Issue by tdav** [ExtCore/ExtCore#192]
здравствуйте. я начал исползовать ExtCore.WebApplication. проблема в плугине начал использовать сборки с локальными репозиториями. при компиляции плагина сторонные сборки dll не копируется в папку плагинов. помогите пожалуйста в чем проблема

**Comment by DmitrySikorsky** [comment]
Здравствуйте! По умолчанию сборки не будут копироваться в папку с расширениями. Это нужно делать либо вручную, либо с помощью какого-то менеджера заданий. Например, Gulp, как тут: https://github.com/ExtCore/ExtCore-Sample/blob/master/src/WebApplication/gulpfile.js

Если открыть тот проект и открыть окно менеджера заданий, то там будет задача "copy-extensions", которая скопирует DLLки в нужное место.
