### ISSUE TITLE
Return int from Save() method in ExtCore.Data.EntityFramework.Storage

### ISSUE THREAD

**Issue by Jantje2000** [ExtCore/ExtCore#194]
The method Save is implemented in the class `Storage`, as we see below:

```csharp
    /// <summary>
    /// Commits the changes made by all the repositories.
    /// </summary>
    public void Save()
    {
      (this.StorageContext as DbContext).SaveChanges();
    }

    /// <summary>
    /// Asynchronously commits the changes made by all the repositories.
    /// </summary>
    public async Task SaveAsync()
    {
      await (this.StorageContext as DbContext).SaveChangesAsync();
    }
```

The `StorageContext` is cast to a `DbContext`, after which `SaveChanges()` or `SaveChangesAsync()` is called. The thing is: `DbContext.SaveChanges()` returns an `int` and `DbContext.SaveChangesAsync()` returns `Task<int>`. This `int` indicates the number of records that have changed in the database.

Especially for validation is this a very convenient feature, because it allows checking whether records are updated - and if not you can take action to find out why they are not updated.

That's why I have the question: would it be possible to return the `int` from `SaveChanges()` and `SaveChangesAsync()`?

**Comment by DmitrySikorsky** [comment]
Hi @Jantje2000, thank you, yes, you are right. I will fix it in next few days.

**Comment by Jantje2000** [comment]
Thank you very much!

**Comment by DmitrySikorsky** [comment]
https://github.com/ExtCore/ExtCore/releases/tag/8.1.0

**Comment by Jantje2000** [comment]
Thank you for your fast help!
