### ISSUE TITLE
Use a MSBuild build project for common props

### ISSUE THREAD

**Issue by iyilm4z** [ExtCore/ExtCore#195]
All projects in the solution have many properties in common. So,  we may use a MSBuild build project for common props to simplify projects and make version changes easier. I realized this issue when I review this commit(https://github.com/ExtCore/ExtCore/commit/8835c39bddbcfb662db188f2f5f06558af4b90fe)

**Comment by iyilm4z** [comment]
We may also remove the `icon.png` file from all projects, move it to the root directory by renaming it `icon-mini.png`, and reference it from the new `common.props` file. It will be another good reusability improvement. WDT?

**Comment by DmitrySikorsky** [comment]
Hi @iyilm4z! Wow, I didn't know about this feature, looks nice. It will make commits reviews much easier. The icon option is good too, but I would name it like nuget_icon.png, to indicate its purpose, not characteristics.

Thank you! I will look at this and merge on the weekend.

**Comment by iyilm4z** [comment]
@DmitrySikorsky, I did some other improvements. 

I used `PackageIconUrl` instead of `PackageIcon`. IMHO it has three advantages. The first is decreasing repo size. The second is the reusability of assets. The third is SEO, which may make traffic to your doc website. You may give a better name to your icon file in the assets folder of your doc website. It's all your choice. I'm also ok with the current name.

I also changed `LangVersion` to the `latest`. This will allow us always keep up with the latest language features. I also added it for my next possible PR which is using the `file-scoped namespace` feature. I like that new language feature. It simplifies code.

Another improvement is using the [SourceLink](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink) library. Nowadays it's like it's everywhere and it's necessary for open-source projects. You may read more about it.

Did you realize that making all these extra cool changes are made in a single file, the common.props file. Without that file, these extra cool changes would require more changes in many files.

**Comment by DmitrySikorsky** [comment]
Thank you, @iyilm4z ! The only issue that `PackageIconUrl` is deprecated.

https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5048

I used to have `PackageIconUrl`, but had the warning every publish to NuGet, so fixed it in a current way. So we should keep `PackageIcon`. What do you think about this?

I think we can finish with this and then continue looking at other improvements, so it will be easier for me to focus on them.

**Comment by iyilm4z** [comment]
@DmitrySikorsky, I got the `PackageIconUrl` case. I'm ok with `PackageIcon`. I can take responsibility for it. So what about the [SourceLink](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink) library? Do you want to do it later?

**Comment by DmitrySikorsky** [comment]
I would start thinking about it after we finish with the initial idea if you don't mind, so we can go with the smaller steps which are easier to look at and understand.

**Comment by iyilm4z** [comment]
Ok. Then I reverted the last 3 commits. So you can review and merge it.

**Comment by DmitrySikorsky** [comment]
@iyilm4z the issue is closed automatically as I've merged the PR, but we can reopen it and continue :)

BTW, I will use this fix in my Platformus and Magicalizer projects too, because there are big number of projects as well.

**Comment by iyilm4z** [comment]
I will close this ticket and create a new issue for each feature.
