### ISSUE TITLE
how to add mongoDb

### ISSUE THREAD

**Issue by ridingmower** [ExtCore/ExtCore#199]
Hello how to add mongoDb.

Also is there a way to prevent DDOS with throttling or prevent bruteforce attacks on the site in the extension

**Comment by DmitrySikorsky** [comment]
Hi @ridingmower,

To add a new DB support you have to implement the IStorage, IStorageContext, and IRepository interfaces.

Please, take a look how it is done for the Dapper support:
https://github.com/ExtCore/ExtCore/tree/master/src/ExtCore.Data.Dapper
https://github.com/ExtCore/ExtCore/tree/master/src/ExtCore.Data.Dapper.SqlServer
