### ISSUE TITLE
Sample not running

### ISSUE THREAD

**Issue by SebastianStehle** [ExtCore/ExtCore#2]
Hi, 

I cannot run the application, I get the following error: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework.

Do you have any tipps?

**Comment by DmitrySikorsky** [comment]
Hi!

Just right-click on the dlls from the archive and uncheck the "unlock" security checkbox.

**Comment by SebastianStehle** [comment]
Thanks for your fast response. I tested the sample and it does not seems to be very easy for development. I have to build and run the gulp task whenever I make any change :(

**Comment by DmitrySikorsky** [comment]
Yes, you have if you use extensions built as dlls. BUT. You can just add direct references to your extension projects in the project.json of the main application. Everything will work (ExtCore will resolve this extensions). This is good for development time. After that you can link them as dlls (without direct references) or as NuGet packages.

**Comment by SebastianStehle** [comment]
Obviously, but I still see some problems and possible improvements:

1. You cannot edit the views at runtime
2. You cannot edit the views on your server (e.g. for small fixes, A/B tests and so on). This is the latest point I would try to fix.
3. There is no solution for static files

What I would do:

a).Register PhysicalFileProvider for each extension in your solution (should be configurable in some kind) for the development environment.
b) Write a custom static file middleware (or configure the existing one) to load static files from the class libraries or the file system (depending on the environment).
c) Develop a file dependency system
d) Find a solution for bundling script and styles from multiple modules for the production environment

What I mean with b is the following system:

Every view can require scripts or styles and configure dependencies between them, for example:

    Scripts.Requires("//cdn.com/jquery.1.9.js")
		   .Alias("jquery");
		   
    Scripts.Requires("~/Areas/Cms/scripts/ckeditor/ckeditor.js")
		   .DependsOn("jquery");

In the layout file you bring the dependencies in the right order. A more advanced solution can also add local fallbacks and versioning, but this is not necessary for the beginning I think.

Btw: I really like your solution so far, it is not criticism, I just want to discuss, how to improve it.

**Comment by DmitrySikorsky** [comment]
Interesting.

What I can say now:

3. There is solution for static files.

Please take a look at https://github.com/platformus.

But now I've found better solution:

https://github.com/DmitrySikorsky/AspNet5Resources

I will implement it in ExtCore in 1.0.0-alpha5 soon.
