### ISSUE TITLE
I noticed you have todo: add error logging

### ISSUE THREAD

**Issue by jvelezc** [ExtCore/ExtCore#21]
So I noticed you have exception handlers todo: implement error logging. What technology are you thinking to implement for error logging? ELM, Nlog? Let me know, and I can start something of that nature as a pull.

**Comment by DmitrySikorsky** [comment]
ExtCore doesn't use any concrete implementation of logger. It uses ILoggerFactory.CreateLogger and ILogger for logging. In the host application (application that uses ExtCore) you can then register some concrete implementation (for example, console logger) and you will have the log messages in the console (please take a look at ExtCore sample). ExtCore Startup class (and all of the extensions) has instance of IServiceProvider that allows it to get instance of ILoggerFactory (you can see how it works). I want to pass ILoggerFactory object to the AssemblyProvider and then create logger of type AssemblyProvider there to log not only error messages, but successful actions too. After that I will remove logging of the loaded assemblies in the foreach loop from the Startup class.

**Comment by KANekT** [comment]
implementation of logger Nlog/ELM must be in example https://github.com/Platformus/Platformus

**Comment by DmitrySikorsky** [comment]
It is done in ExtCore Sample project:
https://github.com/ExtCore/ExtCore-Sample/blob/master/src/WebApplication/Startup.cs#L18

**Comment by DmitrySikorsky** [comment]
As I understand we can add any logger there. Logger just have to implement ILogger.
