### ISSUE TITLE
Does not work with Linux dotnet core 1.0.0-preview2-003121

### ISSUE THREAD

**Issue by gergc** [ExtCore/ExtCore#23]
Compile/build/run sample in Linux and it will not load the extensions. The sample displays a blank page. It works fine on Windows.

**Comment by DmitrySikorsky** [comment]
Is it possible that it is related to the extensions path? Do you have anything in log?

**Comment by gergc** [comment]
I strace'd it executing and it looks like it doesn't even try to open the extensions path, I'll check again later today and let you know if I can find anything else.

**Comment by DmitrySikorsky** [comment]
As we have discussed with you in Gitter, this was a path issue. In Linux we need to specify extensions path like \\Extensions, not like //Extensions. I will add comments. Thank you!
