### ISSUE TITLE
Partial view on two extensions

### ISSUE THREAD

**Issue by Brouilles** [ExtCore/ExtCore#32]
Hello,
I would like to know if there was a way to load via Html.PartialAsync a page of extension 2 to extension 1 ?
I think this may be complicated, or impossible, but I came to have confirmation.

I apologize for my bad English.
Thank you for your answers,
Best regards.

**Comment by DmitrySikorsky** [comment]
Hi! I didn't try PartialAsync, but you can use Partial to render the partial view from the extension A in the view from the extension B. So each extension may use views and resources from other extensions.

**Comment by Brouilles** [comment]
Thank you for your prompt response ! I'll try this.
