### ISSUE TITLE
After upgrading the project to 1.1 The ExtCore not working

### ISSUE THREAD

**Issue by chanaka1** [ExtCore/ExtCore#35]
I have upgraded my project to 1.1 latest release , The ExtCore need upgrading 
The dnxcore50 removed 
NETStandard.Library to 1.6.1
MVC related to 1.1.0

**Comment by DmitrySikorsky** [comment]
Thanks! I think we will need to update ExtCore version to 1.1.0 too. Could you describe why did you remove "dnxcore50"?

**Comment by chanaka1** [comment]
No "dnxcore50" is now integrated directly to the .Net core

**Comment by DmitrySikorsky** [comment]
I understand. Thanks, I will merge, add few other small fixes and update version to 1.1.0.

**Comment by chanaka1** [comment]
Awesome , Thanks.

**Comment by chanaka1** [comment]
@DmitrySikorsky one more thing , after the sample project upgraded to new version do not forget to add run-times to the project.json

Eg: 
"runtimes": {
    "win10-x64": {},
    "osx.10.10-x64": {}
  },

**Comment by KANekT** [comment]
1.1.0 is breakштп sites with SSL.

**Comment by DmitrySikorsky** [comment]
I'm looking at https://github.com/aspnet/Mvc/blob/dev/samples/MvcSandbox/project.json and can't see any `imports` there at all. Same for the EF. Do we still need it? Do you have any good link?

**Comment by chanaka1** [comment]
https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json#frameworks
https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/

The plan is to remove "import" in later versions

**Comment by DmitrySikorsky** [comment]
I have removed it and tested. It seems like it works with no problems. I will test on bigger project too.

**Comment by chanaka1** [comment]
Cool
