### ISSUE TITLE
Replace SetStorageContext method of the RepositoryBase class with the constructor

### ISSUE THREAD

**Issue by DmitrySikorsky** [ExtCore/ExtCore#38]
We need to do that because repository can't work without the storage context set and it also makes things more obvious when this dependency is set in the constructor.

**Comment by DmitrySikorsky** [comment]
Problem is that we can't be sure that the found implementation of the `IRepository` interface has the constructor that have corresponding parameter. So maybe it is not so good idea? We know for 100% that implementation of the `IRepository` has `SetStorageContext` method, but we know nothing about the constructors.

**Comment by Xarkam** [comment]
We are at version 4. Is it still relevant ?

**Comment by DmitrySikorsky** [comment]
I should thing about that. The problem is that the main idea was to make it possible to select the data provider should be used just by copying DLL file and to have a single access point to all the repositories (Unit of Work pattern). I could make the repositories to be services, in this case it would be possible to inject IStorage into them, but that also would mean that it won't work as UoW anymore. I really need to think about overall concept. If you have time to help me I would be happy.

**Comment by DmitrySikorsky** [comment]
...also I would like to add, that we need to make it possible to support different storages at the same time. So, I think it must be totally rethought.
