### ISSUE TITLE
Development Work Flow

### ISSUE THREAD

**Issue by cevarief** [ExtCore/ExtCore#39]
Hi,

How is the development work flow when using extcore, do we need to run gulp task to copy the extension dll to main extension everytime we build the extension project and how to debug the extension since extension does not run on its own.

I'm using visual studio code.

Thanks.

**Comment by KANekT** [comment]
You may use nuget ...

**Comment by cevarief** [comment]
Hi @KANekT care to elaborate regarding to use nuget? Thanks.

**Comment by KANekT** [comment]
if don't need change extcore:
@cevarief https://www.nuget.org/profiles/dmitry.sikorsky

**Comment by cevarief** [comment]
What i mean is how to debug our own custom extension not ExtCore itself.

**Comment by DmitrySikorsky** [comment]
Hi! While development you may have some host application (like ExtCore-Sample one) and have **direct links** to you extension projects in the project.json file. You will be able to debug them as any other ASP.NET project. When extension is ready you can use it by having the direct links in project.json OR by copying to the extensions folder.

**Comment by DmitrySikorsky** [comment]
Hi! I close the issue for now because it seems that it is answered. Feel free to reopen it if have additional questions.
