### ISSUE TITLE
For NET46 Project

### ISSUE THREAD

**Issue by royyuannet** [ExtCore/ExtCore#40]
is this possible for .net 461 project?

**Comment by DmitrySikorsky** [comment]
The only thing that is used in ExtCore that is not supported by .net 461 is https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.WebApplication/AssemblyProvider.cs#L8

So as I understand we will be able to support full .net after .net standard 2... I'm not sure for 100% so I will appreciate any help or advice. Thanks!

**Comment by royyuannet** [comment]
Yes. Thank you for your reply. I try to use Assembly.LoadFrom to support .net 461. The services can be added into the DI. But when i try to use the views in the assembly. It will have a "assembly couldn't be found" error. When i copy the assemblies to the root folder. it will have a "the view data dictionary get the Type A, but it need Type A" error.

**Comment by DmitrySikorsky** [comment]
I will think about how to add .net 461 support. So if you have progress please share so we could move faster. Thanks!

**Comment by royyuannet** [comment]
Hi, after some more test. I figured out a solution. Maybe it is not a better one. But it can resolve my problem now.  This is the code below:
#if NET461
        private List<Assembly> assembliesFromPath;
        private IEnumerable<Assembly> GetAssembliesFromPath(string path)
        {
            assembliesFromPath = new List<Assembly>();
            AppDomain.CurrentDomain.AssemblyResolve += AssemblyResolve;
            if (!string.IsNullOrEmpty(path) && Directory.Exists(path))
            {
                this.logger.LogInformation("Discovering and loading assemblies from path '{0}'", path);

                foreach (string extensionPath in Directory.EnumerateFiles(path, "*.dll"))
                {
                    Assembly assembly = null;
                    try
                    {
                        assembly = Assembly.LoadFile(extensionPath);
                        assembliesFromPath.Add(assembly);
                        this.logger.LogInformation("Assembly '{0}' is discovered and loaded", assembly.FullName);
                    }

                    catch (Exception e)
                    {
                        this.logger.LogWarning("Error loading assembly '{0}'", extensionPath);
                        this.logger.LogInformation(e.ToString());
                    }
                }
            }

            else
            {
                if (string.IsNullOrEmpty(path))
                    this.logger.LogWarning("Discovering and loading assemblies from path skipped: path not provided", path);

                else this.logger.LogWarning("Discovering and loading assemblies from path '{0}' skipped: path not found", path);
            }

            return assembliesFromPath;
        }

        private Assembly AssemblyResolve(object sender, ResolveEventArgs args)
        {
            var assembly = assembliesFromPath.Find(a => a.FullName == args.Name);
            if (assembly == null)
            {
                return null;
            }
            else
            {
                return Assembly.LoadFile(assembly.Location);
            }
        }

#else
        private IEnumerable<Assembly> GetAssembliesFromPath(string path)
        {
            List<Assembly> assemblies = new List<Assembly>();
            if (!string.IsNullOrEmpty(path) && Directory.Exists(path))
            {
                this.logger.LogInformation("Discovering and loading assemblies from path '{0}'", path);

                foreach (string extensionPath in Directory.EnumerateFiles(path, "*.dll"))
                {
                    Assembly assembly = null;
                    try
                    {

                        assembly = System.Runtime.Loader.AssemblyLoadContext.Default.LoadFromAssemblyPath(extensionPath);
                        if (this.IsCandidateAssembly(assembly))
                        {
                            assemblies.Add(assembly);
                            this.logger.LogInformation("Assembly '{0}' is discovered and loaded", assembly.FullName);
                        }
                    }

                    catch (Exception e)
                    {
                        this.logger.LogWarning("Error loading assembly '{0}'", extensionPath);
                        this.logger.LogInformation(e.ToString());
                    }
                }
            }

            else
            {
                if (string.IsNullOrEmpty(path))
                    this.logger.LogWarning("Discovering and loading assemblies from path skipped: path not provided", path);

                else this.logger.LogWarning("Discovering and loading assemblies from path '{0}' skipped: path not found", path);
            }

            return assemblies;
        }
#endif

**Comment by DmitrySikorsky** [comment]
Could you prepare the pull request?

**Comment by DmitrySikorsky** [comment]
As I understand it will be possible to add net461 in the frameworks, right?

**Comment by royyuannet** [comment]
Yes. I don't know how to create a pull request. Need you give me the permission. And I have a attach the cs file. We need only change the AssemblyProvider.cs.
[AssemblyProvider.zip](https://github.com/ExtCore/ExtCore/files/638582/AssemblyProvider.zip)

**Comment by DmitrySikorsky** [comment]
No, everybody can create the pull request. You need to clone the repo, make modifications, and then make a pull requests to the main repo. But thanks for the file, let me look at it, I will test locally.
