### ISSUE TITLE
Make it possible to use Identity with ExtCore.Data

### ISSUE THREAD

**Issue by DmitrySikorsky** [ExtCore/ExtCore#42]
Now StorageContext is inherited from EntityFrameworkCore's DbContext, and it is not possible to change that without need to rewrite the full ExtCore.Data.EntityFramework.Implementation project. We need to think about how to make it possible to use Identity without rewriting the whole project.

**Comment by cybernexus** [comment]
I ended up creating a new implementation. 

Because of the added complexity it may be simpler and even slightly more perform-ant to keep a separate  ExtCore.Data.EntityFramework.SqlServerIdentity project for those who need use of IdentityDbContext.

Once I saw how easy it was to create the new implementation (I think it may have taken me 5 minutes) refactoring the underlying code base to override didn't make a whole lot of sense.

**Comment by DmitrySikorsky** [comment]
I see. But I think that it might be useful for common or shared extensions, that might be used in different projects. I will think about how to fix that.

**Comment by holmescn** [comment]
I that means we can use Identity in ExtCore 1.3.0 on May 26? I am trying to integrate Identity into a ExtCore-based project, but I cannot find any guide. Currently, I copy the Identity code from WebApp template into an extension and trying to make it works. IMO, I use a separate DbContext and perhaps I will keep multiple DbContext in my project. All DbContext connect to the same database.  I don't know if that works or I need to wait for the new version of ExtCore?

**Comment by DmitrySikorsky** [comment]
For now the easies way to do that is just copying of the project and changing base db context to the identity one. But I will try to provide normal ability to set the context ASAP. But I think it can take few weeks.

**Comment by DmitrySikorsky** [comment]
@holmescn So, I have fixed it locally. I will commit in few days, but it will take some time to release 1.3.0-beta1. In few words, StorageContext will now be injected in the Storage by the DI, so you always will be able to replace it with a custom one. Also I created base classes for EF storages, there will be no duplicating anymore. And switching to the Identity data context will be as simple as adding small class. In 10 lines. Please wait a bit :)

**Comment by holmescn** [comment]
@DmitrySikorsky Now I am using an alternative way to complete this: Identity functions are implemented in WebApplication to provide login/logout and other functions. And make ExtCore as an extension infrastructure. That is easy to understand the structure of the application.

**Comment by DmitrySikorsky** [comment]
So, now I have made that IStorageContext is injected by the DI, so IStorage implementation doesn't have hardcoded one. So to use Identity you should create small IdentityStorageContext class (you can just copy one and change the base class) and then inject it. ExtCore will use your storage context.
