### ISSUE TITLE
Make it possible to load extensions at runtime

### ISSUE THREAD

**Issue by DmitrySikorsky** [ExtCore/ExtCore#43]
Now it is only possible to discover and initialize the extensions at runtime. We need to make it possible to add new extensions on the fly.

**Comment by ErcinDedeoglu** [comment]
waiting for this feature +1

**Comment by postb99** [comment]
As far as I know, it was partly due to a .net core 2.0 limitation. What about 2.1 or 3?

**Comment by DmitrySikorsky** [comment]
@postb99 didn't look at it yet. Trying to finish my Platformus project :)

**Comment by cedriclange** [comment]
Was reading about the .net core 3.0 seems like there a new feature ALC added. This one could be a big help to this issue. I got to know ExtCore recently it's a very nice project .

**Comment by Razgort** [comment]
Hello guys would love possibility to add plugin at runtime from a json config file ! is it possible with your solution ?

**Comment by DmitrySikorsky** [comment]
Hi @Razgort, I will look at it when .net 3 beta is released (to save time).

**Comment by DmitrySikorsky** [comment]
So, now I can load an extension at runtime, but IActionDescriptorCollectionProvider caches the collection of the available controller actions, and I can't find the way to invalidate that cache for now.

**Comment by DmitrySikorsky** [comment]
So, I was able to add a controller from a dynamically loaded assembly at runtime (just inside another controller action), then I was able to update cached action descriptors and after that actions from the new controller worked:

```
applicationPartManager.ApplicationParts.Add(
        new AssemblyPart(Assembly.LoadFrom(@"C:\Users\Dmitry Sikorsky\Documents\Projects\ExtCore5\E1\bin\Debug\netcoreapp3.0\E1.dll"))
      );

(this.actionDescriptorCollectionProvider as MyActionDescriptorCollectionProvider).UpdateCollection();
```

I don't like the way it is done, because I had to copy the [DefaultActionDescriptorCollectionProvider](https://github.com/aspnet/Mvc/blob/65af12f1f575fdaee893e0232416df29bb83d7fa/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/DefaultActionDescriptorCollectionProvider.cs) and make its UpdateCollection method public. This class is internal and I don't know which problems it might create. I'm going to try to remove app part and see whether it works too.

**Comment by DmitrySikorsky** [comment]
I succeeded in loading/unloading extensions at runtime, sample app works. I can many times load/unload extension with controller, then load it one more time and try to navigate to the controller, and it works.

**Comment by lrfahmi** [comment]
> I succeeded in loading/unloading extensions at runtime, sample app works. I can many times load/unload extension with controller, then load it one more time and try to navigate to the controller, and it works.

Where is example?

**Comment by DmitrySikorsky** [comment]
> Where is example?

In my laptop so far :) I will start from just moving to .net core 3, then will fix tasks one by one, and publish alphas.

**Comment by lrfahmi** [comment]
Ok. Thank you @DmitrySikorsky .

**Comment by lrfahmi** [comment]
> In my laptop so far :) I will start from just moving to .net core 3, then will fix tasks one by one, and publish alphas.

Could you give me an example of a web api? Load/Unload extensions at runtime?

Thank you.

**Comment by Ratn007** [comment]
Please provide sample to load unload extension at runtime

**Comment by DmitrySikorsky** [comment]
I will try to provide an alpha2 with this features and demo project in few days.

**Comment by DmitrySikorsky** [comment]
So, I’ve spent a lot of time discovering this issue. I can say now that currently it is not possible to implement it in full. While it is easy to load assemblies at runtime, even to create objects or to resolve controllers from them, but there are number of problems that it is not possible to fix for now:

- precompiled views from the dynamically loaded assemblies [are not resolved](https://github.com/aspnet/AspNetCore/issues/17171);
- we can’t change registered routes at runtime;
- we can’t re-execute all the ExtCore actions (configure services action, configure action etc.), especially respecting their priority;
- etc.

While I don’t see any working cases when we really need to load an assembly at runtime without all the features above, I’m closing this issue. We could have something simple like RuntimeAssemblyLoader with load/unload methods and store loaded assemblies inside the ExtensionManager, but as I said, I don’t see any use case for that. It would only make everything a bit more complicated.
