### ISSUE TITLE
Extension with controller having dependency injected through constructor

### ISSUE THREAD

**Issue by pkapare** [ExtCore/ExtCore#47]
I have following scenario:
1. Container MVC application where multiple extensions are plugged in.
2. Various modules are being developed as extensions and plugged into container application mentioned in step 1.
3. Extensions are created with "ASP.Net Core Web Application" template. (Not library but application). Idea here is I should be able to run extension as independent application. Whenever I need to plugin this extension into container I compile it with "emitEntryPoint=false" option.
4. Above setup works fine (except one scenario mentioned in pt. 5 below) and I am able to run extension as independent application as well as plugin it in container and that works too. 
5. Now Extension is having some controllers with dependency injected through controller's constructor. Dependencies are registered in Startup.cs of Extension.  If I build extension and drop it in "Extensions" folder of container application it fails to create instance of such controller with following error.
**Unable to resolve service for type 'ILeadDashboardService' while attempting to activate 'Lead.Controllers.HomeController'**  
I understand this error is because its not able to find dependency registrations which are registered using Extension's Startup.cs. When I manually add missing registrations in Container's Startup.cs it works fine. However its not good solution as everytime I need to add new plugin I will have to add extension's dependencies in container's startup.cs.
Any pointer how I can solve this problem without adding dependency registrations in Container's startup.cs?

**Comment by DmitrySikorsky** [comment]
Hi! If I understand you correctly it should be possible to fix (and it is easy). You need to implement [IExtension](https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.Infrastructure/IExtension.cs#L17) interface in your extensions. Use ConfigureServicesActionsByPriorities to define small pieces of code that will be executed by the ExtCore inside the ConfigureServices method. You can take a look at [ExtCore.Data extension](https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.Data/DataExtension.cs#L50) for the sample.

This class will be used only in "plugin mode", while in "standalone application mode" it will be just ignored.

**Comment by pkapare** [comment]
Thanks for quick response. Let me try it out. Will let you know how it goes.

**Comment by pkapare** [comment]
Perfect. This worked like charm. Thanks for help. One more question I have is currently views from "Extensions" are loaded with its own layout page. Is there any way wherein I can force extension views to use container's layout instead of "extension's" layout page?

**Comment by DmitrySikorsky** [comment]
I think you only may play with the layout path. Why: because as I understand in your application you have many _Layout.cshtml files at once (in different extensions). It is not normal situation and it is not strange that it doesn't work good. You could try to create your own views resolver and it will work for sure. OR you can just exclude that views from build when projects are built as extensions.

**Comment by pkapare** [comment]
I ended up explicitly specifying layout property on view in extension and that worked however it will not work in all scenarios. Time being this workaround has done job. Will check view resolver option to make it more complete solution. Closing the issue. Thanks for your help.
