### ISSUE TITLE
Embeded view are regonised however styles not!

### ISSUE THREAD

**Issue by pkapare** [ExtCore/ExtCore#48]
Views embedded in extension are recognized however Styles are not. I  disassembled extension assembly and styles are present there in assembly as embedded resource along with view. When I am trying to refer embedded style in extension's view using dot (.) notation i.e. Styles.default.css instead of Styles/default.css view is rendered without styles. What could I have done wrong?

**Comment by DmitrySikorsky** [comment]
Have you checked this sample? It uses styles with no problems:
https://github.com/ExtCore/ExtCore-Sample-Mvc/tree/master/src/Extension

**Comment by pkapare** [comment]
Well, I have already tried and debugged this sample and it works fine however there is something wrong in my application because of which embedded styles are not rendered correctly. I will check my application code carefully. Thanks for help.

**Comment by DmitrySikorsky** [comment]
I think this issue can be closed. Feel free to reopen it if have any additional questions.
