### ISSUE TITLE
Extension To Register New Service?

### ISSUE THREAD

**Issue by YodasMyDad** [ExtCore/ExtCore#49]
Say I have an extension which has it's own service

ISomethingService ... SomethingService

And I want to use it in my extensions controllers via DI... Can I register it within the Plugin itself? like

services.AddTransient<ISomethingService, SomethingService>();

Also what about other services which are registered with the IOC at startup in the web project?  Will I have access to those services in my plugin controllers?

**Comment by DmitrySikorsky** [comment]
Hi! Yes and I need to add article about that to the docs. It is easy.

You need to implement [IExtension](https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.Infrastructure/IExtension.cs#L17) interface in your extensions. Use ConfigureServicesActionsByPriorities to define small pieces of code that will be executed by the ExtCore inside the ConfigureServices method. You can take a look at [ExtCore.Data extension](https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.Data/DataExtension.cs#L50) for the sample.

**Comment by YodasMyDad** [comment]
Thanks. All the example solutions are using embedded JSON configuration. Can it work without making the views/assets embedded too?

**Comment by DmitrySikorsky** [comment]
It may work without embedded views/assets, but in this case it will not be able to load them from the extensions (but will be able to load them from the main app as usual) :) You may add your custom IFileProvider implementation and it will work. Also, as I know now it is possible again to use precompiled views.

**Comment by DmitrySikorsky** [comment]
I think this issue can be closed. Feel free to reopen it if have any additional questions.
