### ISSUE TITLE
Add symbols to Nuget package

### ISSUE THREAD

**Issue by bdparrish** [ExtCore/ExtCore#55]
Create a Nuget package that includes the *.pdb files so that debugging is easier.

**Comment by DmitrySikorsky** [comment]
Could you please help me with that? I'm using a bat file to generate NuGet packages (and another one to push them to NuGet).

Pack commands look like this:

```
cd C:\Users\MyUser\Documents\Projects\Web\ExtCore\src\ExtCore.Data
dotnet pack --configuration Release
```

I can add a flag that will generate symbols for the package. If the symbols file is generated NuGet will try to upload it to the symbols storage when I run `nuget push` command.

But this process never finish successfully. It just writes it uploading the symbols and that's all. It doesn't go to the next package. If I remove the symbols it will upload all packages to the NuGet with no problems.

Do you know how to fix that?

**Comment by DmitrySikorsky** [comment]
I will close it for now. Feel free to re-open it any time if you still have questions or comments about this.
