### ISSUE TITLE
Question: Is it possible to add some default Controllers to the framework?

### ISSUE THREAD

**Issue by dfarrNTST** [ExtCore/ExtCore#57]
We would like to add some default Controllers to a project that uses this so we can enforce standard views/services across all Mvc apps that use this...is this possible and how would we go about doing this?  e.g. Create a project that uses this framework, add Controllers for standard REST services and Views for standard items to it, and create a NuGet package out of that so others can use it so that all applications will have those standard Views/Controllers.

**Comment by DmitrySikorsky** [comment]
Hi! Sure. I'm using something like you described in my [Platformus](https://github.com/Platformus/Platformus) project. I have created basic extension named 'Barebone'. It contains all the standard UI features, basic CSS, basic controls. It also contains _Layout.cshtml file too.

Other extensions may have their own views and controllers, but they automatically have all the basic UI and layout.

**Comment by DmitrySikorsky** [comment]
I will close it for now. Feel free to re-open it any time if you still have questions about this.
