### ISSUE TITLE
Windows 10 Core IoT / Ubuntu Linux - would ExtCore be usable with an RPi 3?

### ISSUE THREAD

**Issue by lollisoft** [ExtCore/ExtCore#59]
Hi,

I just have installed my Windows 10 Core IoT on my Raspberry 3 and there seems now be a working ASP.Net Core for it. Do you know if ExtCore will run on that device?

Also I am interested in Ubuntu Linux running an ASP.Net Core app...

Thanks, Lothar

**Comment by DmitrySikorsky** [comment]
Hi Lothar! Oh, you ask very interesting things. Honestly I didn't event think about testing ExtCore web application on the Raspberry device (with ARM CPU as I understand?)

ExtCore is first of all web applications framework, it is hard to imagine that somebody will use such device as a web server, but... I don't know. I would be happy to know the results of your tests.

What about Ubuntu Linux. We have tested it and it works with no problems or issues. Just works.

**Comment by lollisoft** [comment]
Ubuntu may an option for the Rpi and also within my qemu VM environment. I'll go to try all in the next weeks or so. ExtCore seems indeed interesting as of the modular design. My .Net WinForms based DevExpress project uses a CAB framework that is also modular. Just beginning with VM first I think.

**Comment by DmitrySikorsky** [comment]
I will close it for now. Feel free to re-open it any time if you still have questions about this. But it would be very interesting to know the results of your experiments.
