### ISSUE TITLE
IntelliSense not functional in Extensions

### ISSUE THREAD

**Issue by Flying--Dutchman** [ExtCore/ExtCore#61]
When creating MVC Extensions, inside the Views  IntelliSense is not working and throwing a lot of errors. 
(Visual Studio 2017)

![extcore-1](https://cloud.githubusercontent.com/assets/9158539/25557272/acb22a48-2d0e-11e7-80d4-434ca82716ad.PNG)
![extcore-2](https://cloud.githubusercontent.com/assets/9158539/25557274/ae726a1e-2d0e-11e7-8b2c-ab9f4cd2e4b4.PNG)

**Comment by Flying--Dutchman** [comment]
Seems to be a general VS Bug.
Will try this workaround and post my findings:

https://developercommunity.visualstudio.com/content/problem/28408/net-core-razor-intellisense-in-class-library.html

**Comment by DmitrySikorsky** [comment]
I have the same problem too. I think it is because VS doesn't consider the dlls as web projects.

**Comment by Flying--Dutchman** [comment]
Exactly. The SDK is different.
In the link I mentioned above, you can change the SDK in the csproj file to get intellisense working

**Comment by DmitrySikorsky** [comment]
I think we can now close this issue. Fill free to reopen it if have any additional questions/ideas.

**Comment by Flying--Dutchman** [comment]
I think it should be added in the tutorial, docs and examples. 
Also maybe a FAQ page on extcore.net. Not having IntelliSense is a major motivation and performance killer (yes, yes we are spoiled with vs ;) )

As soon as I have the time, I will write something in the docs.

**Comment by shayanblest** [comment]
I tried to changing
   `<Project Sdk="Microsoft.NET.Sdk">`
to 
   `<Project Sdk="Microsoft.NET.Sdk.Web">`
and adding 
`<PropertyGroup>`
`   <OutputType>Library</OutputType>`
`</PropertyGroup>`
to Extension.csproj file, the issue was solved.

**Comment by DmitrySikorsky** [comment]
@shayanblest Yes, as mentioned above, it is VS bug. I saw somewhere that it would be fixed.

**Comment by jasselin** [comment]
Fixed in 15.3 
https://github.com/aspnet/Tooling/issues/1013

**Comment by DmitrySikorsky** [comment]
@jasselin good to know, thank you!
