### ISSUE TITLE
Replace Startup class inheritance with AddExtCore and UseExtCore extension methods

### ISSUE THREAD

**Issue by XpectIT** [ExtCore/ExtCore#66]
Hi, I just started with the ExtCore tutorials and just came to the startup class and was a bit...well shocked.

In my opinion its is by far not a good practice that an library such as ExtCore requires the startup class to be inherited from an internal one.

 - what would you do if another library would require the same? You simply could not use them both in that case
 - The configure method is critical as the order of the request pipeline is important. If you have to overwrite it from the base class you  loose a lot of control on what happens when and in which order

So is this really necessary? Usually you would not need anything else than 
 - adding some service if required in the ConfigureServices method
 - in the configure method you will have to call something like app.UseExtCore or so

Also, I am a bit a controll freak and as the startup is essential I simply do not want to loose any controll and provide my own startup class from the base, is this possible?

**Comment by XpectIT** [comment]
Just one more thing: I have extend my configure method s.t an IApplicationLifetime object gets passed as param. Unfortunately this results in errors as there are now 2 configure methods but the framework supports only one. Of course I could just override the configure method and retrieve IApplicationLifetime from the IApplicationBuilder.ApplicationServices, but once again this seems like an unnecessary foreign matter that sould not be required

**Comment by DmitrySikorsky** [comment]
Yes, maybe that is not the best idea to inherit the Startup class, but the other option is to force user to call ExtCore's method in the Startup class ones, it seems a bit more complicated for me. I think I should  make it possible to avoid inheriting the Startup class and allow to call that methods manually. So we will have both the options.

For now you still can control the order of the services/middleware is registered using the prioritized actions. And you can get any service inside the Configure method too using the service provider.

**Comment by DmitrySikorsky** [comment]
The main idea is that ExtCore needs to execute some methods in order to discover the assemblies, to register services and middleware from the extensions etc. So Startup class must  execute them. If user doesn't do that, ExtCore will not work. That's why I decided to use inheritance like the most semantically correct way to do that.

**Comment by XpectIT** [comment]
I agree with you that the user has somehow to setup ExtCore, but I think that the state-of-the-art solution indented by Microsoft is to provide extensions to IServiceCollection and/or IApplicationBuilder. You see that often in their own examples and middlewares. I just have an simple example at hand: https://www.hangfire.io/

 - in ConfigureServices you simply Call services.AddHangfire(x => x.UseSqlServerStorage(this.configurationRoot.GetConnectionString(Constants.ConnectionStringName)));
 - and in Configure you would call app.UseHangfireServer();

I just took a look at your startup class, I think you could easily provide two extensions that perform all that stuff. It basically only copy & paste and you could still use the startup class s.t existing users do not need to change anything. Additionally you open up for more complex usage scenarios. For example: if you have something like service.AddExtCore() you could pass in optional settings so if a users likes to read settings from somewhere else than the app.setttings.json file, that would easily be possible

**Comment by DmitrySikorsky** [comment]
Thank you for the input, it is useful. Now I need to think how and where should I discover the assemblies. Now it is done at the beginning of the ConfigureServices, but I don't really like it, I think it is not good place to do that. Maybe I should take a look at creating extension method for WebHostBuilder. Like UseExtCore() as you have mentioned. It will process assembly discovering etc. Need to think.

**Comment by XpectIT** [comment]
Have a look at how Middleware should be implemented. I think you can discover the assemblies in that extension method. i.e something like

`public static IServiceCollection UseExtCore(this IServiceCollection services)
{
      this.DiscoverAssemblies();

      foreach (IExtension extension in ExtensionManager.Extensions)
      {
        extension.SetServiceProvider(this.serviceProvider);
        extension.SetConfigurationRoot(this.configurationRoot);
      }

      foreach (Action<IServiceCollection> prioritizedConfigureServicesAction in this.GetPrioritizedConfigureServicesActions())
      {
        this.logger.LogInformation("Executing prioritized ConfigureServices action '{0}' of {1}", this.GetActionMethodInfo(prioritizedConfigureServicesAction));
        prioritizedConfigureServicesAction(services);
        this.RebuildServiceProvider(services);
      }
}`

**Comment by DmitrySikorsky** [comment]
Yes, but I think that it is not the best place. Assembly discovering should be called somewhere between Startup class constructor and ConfigureServices... I don't know for now how to do that. Will look at WebHostBuilder, maybe it will help.

**Comment by DmitrySikorsky** [comment]
https://github.com/aspnet/Hosting/issues/1071

This is good link to look at.

**Comment by DmitrySikorsky** [comment]
@XpectIT so, you are right! I decided to add two methods:
AddExtCore
UseExtCore

Startup class will be marked as Obsolete, so it will not break anything.

It will be a part of 1.3. Thank you for the idea!

**Comment by holmescn** [comment]
This is a good discussion. Expect the new version.

**Comment by DmitrySikorsky** [comment]
This is already in NuGet :) You can test version 2.0.0-alpha1. ExtCore-Sample and ExtCore-Sample-Accounting are moved to it. Thanks @XpectIT for the idea.
