### ISSUE TITLE
Initialize the Extension Database Tables 

### ISSUE THREAD

**Issue by shayanblest** [ExtCore/ExtCore#72]
can Initialize The new extensions database tables when initializing the extension instead creating tables manual ?

**Comment by DmitrySikorsky** [comment]
For now I didn't try that (as well as migrations), but I will try to test and describe this in the article.

**Comment by DavidNorena** [comment]
@DmitrySikorsky so you mean we can't use migrations neither initializing them in extension ?

**Comment by shayanblest** [comment]
@DavidNorena Using migrations in cmd or in c# codes at the ConfigureAction Class ?
I can't found any classes or methods to create table and seed data to the database...

**Comment by DmitrySikorsky** [comment]
I just don't use migrations in my projects based on ExtCore or  Platformus (I'm using manual db handling), so I simply didn't try. I will appreciate of  you could help me with that. I think if it doesn't work from the box we need to take a look at the migrations source code and see how it works, so we could make it work in our case.

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please, feel free to reopen it if you have any additional questions or information.

BTW: currently (3.1.0+) ExtCore supports migrations: http://docs.extcore.net/en/latest/getting_started/using_migrations.html
