### ISSUE TITLE
Make Group MenuItems

### ISSUE THREAD

**Issue by Xarkam** [ExtCore/ExtCore#73]
Hello, 

I search to make group of menu items. I looking in Platformus but the structure is totally different of examples.

Would it be possible to have an example with a group of menu items ?

Thanks.

**Comment by DmitrySikorsky** [comment]
Hi! This is very simple task. Just describe some interface that has property that returns MenuGroups for you. Each menu group has property to get menu items of that menu group. Than you will be able to get all the implementations of your interface from all the extensions (using ExtCore), and then - to get the menu groups from that implementations. When you have the collection of the menu groups just get menu items from each of them.
