### ISSUE TITLE
Is ExtCore core 2.0 compatible?

### ISSUE THREAD

**Issue by postb99** [ExtCore/ExtCore#78]
Hi Dmitry,

I tried to upgrade our application to .net core 2.0 as you can see [on this branch](https://github.com/OSAMES/Base/tree/feature/security_extension) but the application crashes at startup [when activating extcore](https://github.com/OSAMES/Base/blob/feature/security_extension/WebApplication/Startup.cs#L23).

The error message says:

> System.MissingMethodException: Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)

I double-checked the nuget packages and the compiled extensions dlls. Do you think that ExtCore is not compatible with netcore 2.0 or could it be something else?

**Comment by DmitrySikorsky** [comment]
I have moved ExtCore to .NET Core 2 locally. I will release new version (it will be ExtCore 3.0.0-alpha1) in few days, so you could move on it.

**Comment by Xarkam** [comment]
Good :)

In the meantime, we have other projects to test their migration on .NET Core

**Comment by DmitrySikorsky** [comment]
So, now you can use ExtCore 3.0.0-alpha1 - it is moved to .NET Core 2.

**Comment by postb99** [comment]
Yes I successfully used extcore 3.0 alpha1 today. Thanks !
