### ISSUE TITLE
Duplication if twice the extension dll

### ISSUE THREAD

**Issue by postb99** [ExtCore/ExtCore#80]
Hello Dmitry,

After upgrading to ExtCore 3.0 alpha1, I noticed that my menu items were duplicated. Indeed, I have my extensions dlls physically present twice: once in webapp's Extensions folder, the second time in webapp's bin folder because there are references (to extensions in webapp project) for debugging purposes.

Is this a bug or feature? I didn't notice this with ExtCore 2.0.
Once I have a single dll of each extension, no problem anymore.

**Comment by DmitrySikorsky** [comment]
Hi! This is correct behavior for now, because ExtCore just loads everything it can found and then use to discover types. But you are right, it is a bit strange. I think we should add some checking, and if the assembly is already present in ExtCore's ExtensionManager, we mustn't load it again.
