### ISSUE TITLE
Extensions View Layout 

### ISSUE THREAD

**Issue by shayanblest** [ExtCore/ExtCore#81]
How can I Assign _Layout page for each Extension separately ? 
For example I have 2 extension that names of them are Admin and Blog and when I assign _Layout.cshtml file for both of blog and admin extensions pages, Blog Extension Pages are using Admin Extension Layout.cshtml ... 
What can I do ?

**Comment by DmitrySikorsky** [comment]
I you have blog and admin parts I would suggest you to separate them using areas. Admin is very good candidate to be an area. But if you don't want to do that, you can go with standard way of fixing task like that. Set some _Layout.cshtml as layout for most of the pages and in some pages just re-assign it with another layout (this.Layout = ... in the view).

**Comment by DmitrySikorsky** [comment]
Please, feel free to reopen this issue if you still have any questions.

**Comment by shayanblest** [comment]
Can I separate the extensions using areas ? 
if its possible , how I can do that ?

**Comment by DmitrySikorsky** [comment]
Sure. With no problems. Just put your area in a separate project and it will work. Take a look at github.com/Platformus/Platformus, Backend projects. They all contain part of the backend areas. Please, ask if have more questions.
