### ISSUE TITLE
Multitenancy

### ISSUE THREAD

**Issue by DavidDury** [ExtCore/ExtCore#83]
Do you have any plans to support multi-tenancy?

**Comment by DmitrySikorsky** [comment]
Yes. It's not so easy. I think we will have to write custom view, controller and view component locators, so they could find ones depending on the profile we need. So one application will have 'different' sets of the types and assemblies available for the types/MVC features discovery. What do you think about that?

**Comment by treefishuk** [comment]
I've been using saaskit alongside ExtCore which seems to play nice : https://github.com/saaskit/saaskit

**Comment by DmitrySikorsky** [comment]
So, for now I think that ExtCore has nothing to do with multitenancy. The applications on top of the ExtCore have. For example, now I create some SAAS solution for business, and there I have that feature by having AccountId field in all of the top level entities. ExtCore is too basic for that.
