### ISSUE TITLE
Exception thrown in Configure Services

### ISSUE THREAD

**Issue by ghost** [ExtCore/ExtCore#86]
after downloading the sample: [ExtCore-Sample-Simplest](https://github.com/ExtCore/ExtCore-Sample-Simplest) I then upgraded to Core 2.0

I now see this problem:

Hope you can help, Cheers, John - Perth Australia

` public void ConfigureServices(IServiceCollection services)
    {
      services.AddExtCore(this.extensionsPath);  //line 32 - exception thrown
    }`

`System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at ExtCore.WebApplication.Extensions.ServiceCollectionExtensions.AddExtCore(IServiceCollection services, String extensionsPath)
   at WebApplication.Startup.ConfigureServices(IServiceCollection services) in C:\Users\John\Downloads\ExtCore-Sample-Simplest-master\ExtCore-Sample-Simplest-master\src\WebApplication\Startup.cs:line 32
`

**Comment by DmitrySikorsky** [comment]
Hi! Simplest sample is not moved to ExtCore 3.0.0 still (which is based on .NET Core 2.0). All the samples will be moved to new ExtCore 3.0.0 when it is released, now it is only ExtCore Sample moved to the new version. So other samples work on .NET Core 1.1 still.

**Comment by DmitrySikorsky** [comment]
Please, feel free to reopen this issue if you still have any questions.
