### ISSUE TITLE
Need explanation

### ISSUE THREAD

**Issue by VSG24** [ExtCore/ExtCore#9]
I'm not quite sure what this framework does. So here is my question:

?- Using this framework am I able to make an ASP.NET Core web app that supports plugins (modules)? (Modules that are written by me or third party to extend or change the functionality of the application)

**Comment by DmitrySikorsky** [comment]
Yes exactly!

While we have so poor documentation you can take a look at the sample project and at https://github.com/Platformus/Platformus (big project based on ExtCore).

**Comment by VSG24** [comment]
I had a look at that CMS but the source code is quite large, It would be nice if you could provide a simpler app to showcase this framework. Maybe a simple SPA with the ability to extend using plugins. That would make the purpose of your framework more clear to the users.

**Comment by DmitrySikorsky** [comment]
Have you looked at https://github.com/ExtCore/ExtCore-Sample ?

**Comment by DmitrySikorsky** [comment]
And you can also try to get help here: https://gitter.im/ExtCore/ExtCore
