### ISSUE TITLE
[Question] How to perform join query?

### ISSUE THREAD

**Issue by postb99** [ExtCore/ExtCore#92]
Hi Dmitry,

Learning EF Core, I see that in each repository I have a DbSet<T>, i.e. a set of records from a single table.

How do I write code that performs a join query? I'd linke to get the user's roles by a single query on "role" and "userRole" tables, but I would need to access to the dbSet's "parent", the database context. In fact I get it as "this.storageContext" that is a DbContext, but then?

Thank you for your time for helping on using EF Core.

**Comment by DmitrySikorsky** [comment]
Hi! You can use navigation properties to have join queries. Also you can use raw SQL queries (I prefer the second option for the complicated scenarios).

**Comment by postb99** [comment]
An elegant (readable) solution [here](https://github.com/OSAMES/Base/blob/master/Security.Data.EntityFramework/PermissionRepository.cs#L37).

Just create the class that holds the custom result of the join query.
