### ISSUE TITLE
IConfigureAction not working in extensions

### ISSUE THREAD

**Issue by shayanblest** [ExtCore/ExtCore#93]
After updating to version 3.0.0, The class(ConfigureAction) that derived from IConfigureAction Interface ,in extensions not working.

**Comment by DmitrySikorsky** [comment]
Hi! Could you provide some code? Maybe you don't have a reference on that project and didn't copy the dll to the extensions folder? It should just work with no problems.

**Comment by shayanblest** [comment]
@DmitrySikorsky  I Fix it.  I just changed the class to public and it worked. 
sorry... 
in version 1 non public ConfigureAction classes were working at here

**Comment by DmitrySikorsky** [comment]
You are right, now ExtensionManager looks in ExportedTypes, not in all types of the assembly. It is done to improve performance. I should have written about that in the release notes.
