### ISSUE TITLE
What if we don't want to use embeded files? [not an issue]

### ISSUE THREAD

**Issue by iyilm4z** [ExtCore/ExtCore#99]
This simple and great project uses resources(views, css, js) as embedded. For development processes i dont want to use this feature, and i want to see all of static files in Extentions folder like Host>Extentions>Extention1>Views. [NopCommerce](https://github.com/nopSolutions/nopCommerce) manages its plugins in this way. Its good because it makes you to be able to make changes on static files of extentions/plugins without building them. Even in production env, i don't want to use embedded resources. What do you think about **resources as content** feature? I also can help with this but first i wanted to ask you. Thanks.

**Comment by DmitrySikorsky** [comment]
Hi Ismail! First of all, thank you for you interest to this project.

You are not the first who requests this feature. I think it could be a great idea, but we need to discuss it first. I think, while development (when extensions are added as implicit dependencies, not as dlls), it could be very useful to resolve static content from the project folders. So it will allow to avoid rebuilding in order for the changes in views,css or js to be applied. Your scenario might work too, but let's start from defining all the use cases we need.

**Comment by iyilm4z** [comment]
**spasibo za bystryy otvet!)** resources of plugin/module/extention we have mostly 3 use cases which is similar to IFileProvider's use cases(Physical, Embedded and Composite). you already did  Embedded one. When i first took a look at the project i thought you use [CompositeFileProvider](https://github.com/ExtCore/ExtCore/blob/master/src/ExtCore.Mvc/CompositeFileProvider.cs) for composing Physical and Embedded use cases. Well.. i think this feature is important and it will make ExtCore much more flexible.

**Comment by DmitrySikorsky** [comment]
#71

**Comment by DmitrySikorsky** [comment]
I'm thinking about splitting the ExtCore.Mvc extension into 3:

ExtCore.Mvc
ExtCore.Mvc.FileProviders.Embedded
ExtCore.Mvc.FileProviders.Physical

So developer will be able to choose how he wants his static content to be added.

Maybe we also should make it possible to have some mixed option...

**Comment by sparkeh9** [comment]
With ExtCore.Mvc.FileProviders.Physical, would files be copied into the main webroot or something?

**Comment by DmitrySikorsky** [comment]
I think with this option you will just be able to specify relative path. But I don't know for now. Maybe we should be able to specify different root paths at the same time. I mean, I think we have 3 cases:

1. Developer works on some extension and doesn't want to rebuild his projects each time some static file (CSS, JS, ...) is changed. I often have this problem. In this case we could add extension project wwwroot paths as alternative roots and use relative URLs in the app.
2. Developer wants extension to consist not only from the DLL files, but from some static files too, so it would be possible to copy it to some /Extensions/SomeExtensionName folder and use from that place.
3. Developer wants everything to work as it is now, so he just adds a NuGet reference (or copy a DLL file) and everything works and static files are used as compiled resources.

**Comment by mitja-p** [comment]
I believe there should be an option to skip automatic discovery and usage of embedded files or at least better control over which assemblies use which access. (when there will be two options) For example I might have server only assemblies that I do not want to be searched for content as there is no static or embedded content there.

Secondly I think adding specific paths and using physical files would be great. And there must be an option of mix and match. So using embeded here, physical there, or multiple. Maybe an additional interface in plugin where you could specify this options. Totally optional of course and by default it should work out of the box.

**Comment by Armarr** [comment]
On our project we made a workaround for this issue.
Each plugin copies the contents of static_files on build.
`''<None Include="static_files\**\*">      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>'''`
Then for release mode I bind a file provider to that folder. For dev mode we want to bind to the files directly so we can make changes without a rebuild. This part is a bit more hacky.

```
var extAssemblies = ExtensionManager.GetImplementations<IExtensionMetadata>().Select(ext => ext.Assembly).ToList();

//Static files
//Development mode: load directly from extension folder > no rebuilds needed
//Release mode: load from site root, copied there by build action
if (hostingEnv.IsDevelopment())
{
	extAssemblies.ForEach(ext =>
	{
		var projectPath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), @"..\..\..\..\");
		var extStaticFilesPath = Path.Combine(projectPath, ext.GetName().Name, "static_files");

		if (Directory.Exists(extStaticFilesPath))
		{
			app.UseStaticFiles(new StaticFileOptions
			{
				FileProvider = new PhysicalFileProvider(extStaticFilesPath),
				RequestPath = "/static_files"
			});

			app.UseDirectoryBrowser(new DirectoryBrowserOptions
			{
				FileProvider = new PhysicalFileProvider(extStaticFilesPath),
				RequestPath = "/browse_static_files"
			});
		}					
	});
}
else
{
	app.UseStaticFiles(new StaticFileOptions
	{
		FileProvider = new PhysicalFileProvider(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "static_files")),
		RequestPath = "/static_files"
	});
}
```

**Comment by DmitrySikorsky** [comment]
It will be done in #168.
